"""Which client profiles ``trw_instructions_sync`` drives, and why the rest are not.

Belongs to the ``_agents_md.py`` facade; re-exported there so importers keep a
single entry point.

Split out because this is a *registry*, and registries of a closed set need to be
readable as one thing. ``_INSTRUCTION_SYNC_CLIENT_IDS`` previously named three of
the seven client profiles with no companion exclusion set and no totality test. A
profile absent from the table takes the same code path as "nothing to do", so the
omission was structurally invisible — which is how ``antigravity-cli`` shipped a
working ``ANTIGRAVITY.md`` generator that the delivery-time sync could never
reach (wiring-defect pattern P11: subset registry with no derivation).

The fix that matters is not the missing entry but the mechanism that makes the
next omission impossible: every profile MUST appear in exactly one of the two
collections below, and ``tests/test_instruction_sync_client_coverage.py`` asserts
that union is total against the profile registry.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Literal, TypeAlias, TypeGuard

import structlog

logger = structlog.get_logger(__name__)

InstructionClientId: TypeAlias = Literal["opencode", "codex", "copilot", "antigravity-cli"]
InstructionGeneratorResult: TypeAlias = dict[str, list[str]]
InstructionSyncGenerator: TypeAlias = Callable[[Path, bool, "dict[str, str] | None"], InstructionGeneratorResult]

#: Profiles whose instruction file is (re)generated by the delivery-time sync.
INSTRUCTION_SYNC_CLIENT_IDS: tuple[InstructionClientId, ...] = (
    "opencode",
    "codex",
    "copilot",
    "antigravity-cli",
)

#: Profiles deliberately handled by another path, each with the reason. This is
#: the mechanism, not documentation — an entry here is a claim a test checks.
INSTRUCTION_SYNC_EXCLUSIONS: dict[str, str] = {
    "claude-code": "CLAUDE.md is written by the carrier path in _profile_dispatcher",
    "cursor-cli": "declares instruction_path=AGENTS.md, refreshed by the AGENTS.md write",
    "cursor-ide": "writes .cursor/rules/*.mdc through the bootstrap IDE-target path",
}


def is_instruction_sync_client(client_id: str) -> TypeGuard[InstructionClientId]:
    """Return whether the client has a real instruction-file generator."""
    return client_id in INSTRUCTION_SYNC_CLIENT_IDS


def _detect_opencode_model_family(project_root: Path) -> str:
    """Read ``opencode.json`` and return the detected OpenCode model family."""
    from trw_mcp.bootstrap._opencode import detect_model_family

    opencode_json_path = project_root / "opencode.json"
    if not opencode_json_path.exists():
        return "generic"

    try:
        import json

        opencode_data = json.loads(opencode_json_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return "generic"
    return detect_model_family(opencode_data)


def _managed_manifest_hashes(project_root: Path) -> dict[str, str] | None:
    """Return the on-disk managed-artifacts content-hash baseline for *project_root*.

    ``.opencode/INSTRUCTIONS.md`` and ``.codex/INSTRUCTIONS.md`` are rendered
    whole, so the only way to tell a stale TRW-owned file from one the user
    hand-edited is to compare it against the hash recorded when TRW last wrote
    it. Without a baseline ``_is_user_modified`` cannot answer and returns
    ``False`` — "could not verify" degrades to "overwrite".

    Only correct for a standalone sync (``trw_instructions_sync``), where the
    manifest on disk still describes the last TRW write. Inside
    ``update-project`` the manifest is rewritten from current on-disk content
    *before* this path runs, which launders a user's edit into the baseline —
    so that flow threads its own pre-write baseline in instead of calling this.
    Returns ``None`` on a first-run project or a pre-content-hash manifest,
    which preserves create/refresh behaviour.
    """
    from trw_mcp.bootstrap._version_manifest import _manifest_content_hashes, _read_manifest

    try:
        return _manifest_content_hashes(_read_manifest(project_root))
    except Exception:  # justified: fail-open — an unreadable manifest must not break the sync
        logger.warning("instruction_manifest_hashes_unavailable", project_root=str(project_root), exc_info=True)
        return None


def _generate_opencode_instruction_target(
    project_root: Path,
    force: bool = False,
    manifest_hashes: dict[str, str] | None = None,
) -> InstructionGeneratorResult:
    """Generate the OpenCode instruction file."""
    from trw_mcp.bootstrap._opencode import generate_opencode_instructions

    return generate_opencode_instructions(
        project_root,
        _detect_opencode_model_family(project_root),
        force=force,
        manifest_hashes=manifest_hashes if manifest_hashes is not None else _managed_manifest_hashes(project_root),
    )


def _generate_codex_instruction_target(
    project_root: Path,
    force: bool = False,
    manifest_hashes: dict[str, str] | None = None,
) -> InstructionGeneratorResult:
    """Generate the Codex instruction file."""
    from trw_mcp.bootstrap._opencode import generate_codex_instructions

    return generate_codex_instructions(
        project_root,
        force=force,
        manifest_hashes=manifest_hashes if manifest_hashes is not None else _managed_manifest_hashes(project_root),
    )


def _generate_copilot_instruction_target(
    project_root: Path,
    force: bool = False,
    manifest_hashes: dict[str, str] | None = None,
) -> InstructionGeneratorResult:
    """Generate the Copilot instruction file.

    Copilot's writer is a marker-based smart merge, so it preserves user prose
    structurally and takes no hash baseline.
    """
    del manifest_hashes
    from trw_mcp.bootstrap._copilot import generate_copilot_instructions

    return generate_copilot_instructions(project_root, force=force)


def _generate_antigravity_instruction_target(
    project_root: Path,
    force: bool = False,
    manifest_hashes: dict[str, str] | None = None,
) -> InstructionGeneratorResult:
    """Generate the Antigravity CLI instruction file (``ANTIGRAVITY.md``).

    The generator already existed but was reachable only from the install-time
    bootstrap path, so the delivery-time ``trw_instructions_sync`` — the call the
    protocol mandates — never refreshed this client's primary surface.

    Like Copilot, this writer is a marker-based smart merge and takes no hash
    baseline.
    """
    del manifest_hashes
    from trw_mcp.bootstrap._antigravity_cli import generate_antigravity_instructions

    return generate_antigravity_instructions(project_root, force=force)


_INSTRUCTION_SYNC_GENERATORS: dict[InstructionClientId, InstructionSyncGenerator] = {
    "opencode": _generate_opencode_instruction_target,
    "codex": _generate_codex_instruction_target,
    "copilot": _generate_copilot_instruction_target,
    "antigravity-cli": _generate_antigravity_instruction_target,
}


#: Clients that keep an INLINE block because no include mechanism works for them
#: (PRD-CORE-240-FR06). Verified against vendor primary sources 2026-07-28:
#:
#: - ``cursor-cli``      — nothing documented for AGENTS.md, its only carrier.
#: - ``cursor-ide``      — ``.cursor/rules/*.mdc`` ``@file`` IS documented, but a
#:   Cursor staff reply (forum.cursor.com/t/135663, Oct 2025) confirms it "doesn't
#:   work yet", with no changelog fix through 2026-07-28. Building on a documented
#:   but non-functional include ships a rule whose body resolves to nothing.
#: - ``antigravity-cli`` — no import syntax found in any source; separately, the
#:   ``ANTIGRAVITY.md`` filename TRW writes is itself unconfirmed against vendor
#:   docs.
#:
#: This is a DECLARED EXCLUSION SET, not a comment: `tests/test_instruction_
#: include_matrix.py` asserts it equals the set of profiles that resolve to
#: INLINE, so a client can only be excluded by decision, never by accident.
#:
#: RE-CHECK TRIGGER: revisit when Cursor's changelog reports a fix for `@file`
#: in `.mdc` rules, or when Antigravity documents an include syntax. Removing an
#: entry requires re-verifying against that vendor's primary docs first —
#: FRAMEWORK-CORE holds that for light clients the generated instruction file IS
#: the protocol carrier, so a broken include costs them the protocol entirely.
#: copilot was moved IN after its capability was re-verified: the `@relpath`
#: syntax is documented for the Copilot CLI only, and this one profile also
#: serves Copilot Chat in VS Code, whose docs describe no inclusion syntax
#: for `.github/copilot-instructions.md`. Capability that varies per SURFACE
#: must be declared at the weakest surface the profile serves.
INCLUDE_INCAPABLE_CLIENTS: tuple[str, ...] = ("copilot", "cursor-cli", "cursor-ide", "antigravity-cli")
