"""OpenCode model-family instruction renderers — part of claude_md static sections.

PRD-CORE-115 FR04/FR05: Produces materially different instruction content for
each model family (qwen, gpt, claude, generic) covering context budget, reasoning
syntax, tool-use patterns, and known limitations.

Public surface: render_opencode_instructions(model_family)
"""

from __future__ import annotations


def render_qwen() -> str:
    """Render OpenCode instructions optimised for Qwen (local vLLM).

    Context: 32K budget, vLLM transport, /think tags for reasoning,
    known vLLM streaming bug on tool calls.
    """
    return (
        "# Qwen-Coder-Next TRW Instructions\n"
        "\n"
        "## Context Budget\n"
        "\n"
        "Qwen models on vLLM have a **32K context window**. Keep instructions and "
        "prompts concise. Call `trw_checkpoint()` before context-heavy operations "
        "to compact the window. Do NOT paste large files inline — reference by path.\n"
        "\n"
        "## Workflow\n"
        "\n"
        "1. **Start**: call `trw_session_start()` — loads prior learnings\n"
        "2. **Think before acting**: for complex tasks, use `/think` tags to reason "
        "step-by-step before making tool calls\n"
        "3. **Keep tasks bounded**: 1-3 files per task is optimal for 32K context\n"
        "4. **Verify**: run tests after each change — fix failures before moving on\n"
        "5. **Learn**: call `trw_learn()` when you discover a gotcha or pattern\n"
        "6. **Finish**: call `trw_deliver()` — persists work for future sessions\n"
        "\n"
        "## Ceremony Protocol\n"
        "\n"
        "- `trw_session_start()` — **first action** in every session\n"
        "- `trw_checkpoint(message)` — after each milestone; enables resume on crash\n"
        "- `trw_learn(summary, detail)` — for gotchas, patterns, error workarounds\n"
        "- `trw_deliver()` — **last action**; syncs instruction file and persists learnings\n"
        "\n"
        "## Reasoning Patterns\n"
        "\n"
        "Qwen3-Coder-Next supports `/think` ... `/think` blocks for extended reasoning:\n"
        "```\n"
        "/think\n"
        "Break down what files need to change and why before making any edits.\n"
        "/think\n"
        "```\n"
        "Use `/think` blocks for: architectural decisions, multi-file refactors, "
        "debugging root-cause analysis. Skip for trivial edits (≤3 lines).\n"
        "\n"
        "## Structured Output Conventions\n"
        "\n"
        "- Issue direct tool calls — do not wrap in JSON envelopes\n"
        "- Use explicit file paths: never assume cwd\n"
        "- Prefer concise, targeted instructions over verbose context dumps\n"
        "- Validate tool arguments locally before issuing calls\n"
        "\n"
        "## Tool-Use Best Practices\n"
        "\n"
        "- Call one TRW tool at a time — vLLM streaming has a known parser bug that "
        "can cause silent agent loop crashes on concurrent or malformed tool calls "
        "(anomalyco/opencode#16488)\n"
        "- If a tool call produces no output or the agent appears stuck, restart the "
        "session and call `trw_session_start()` to recover the last checkpoint\n"
        "- Prefer `trw_recall(query)` before re-implementing known patterns\n"
        "\n"
        "## Known Limitations\n"
        "\n"
        "- **32K context cap**: avoid loading large files; use targeted reads\n"
        "- **vLLM streaming bug**: tool call XML parsing can silently fail on "
        "concurrent calls; issue calls sequentially\n"
        "- **No Agent Teams**: Qwen via OpenCode does not support multi-agent "
        "peer coordination — use focused sequential tasks instead\n"
        "- **Model tag required**: OpenCode requires exact model tag "
        "(e.g., `vllm/Qwen/Qwen3-Coder-Next-FP8`) — bare names silently fail\n"
        "\n"
        "## Framework Reference\n"
        "\n"
        "Read `.trw/frameworks/FRAMEWORK.md` at session start — it defines the "
        "methodology and quality gates your tools implement.\n"
    )


def render_gpt() -> str:
    """Render OpenCode instructions optimised for GPT models (OpenAI API).

    Context: 128K+, structured JSON mode, chain-of-thought, o3/o1 reasoning.
    """
    return (
        "# GPT TRW Instructions\n"
        "\n"
        "## Context Budget\n"
        "\n"
        "GPT-4o and GPT-5.x have a **128K+ context window**. Reasoning models "
        "(o3, o1) have extended token budgets for chain-of-thought. Use the full "
        "budget for complex multi-file tasks — no need to compress aggressively. "
        "Call `trw_checkpoint()` at phase boundaries.\n"
        "\n"
        "## Workflow\n"
        "\n"
        "1. **Start**: call `trw_session_start()` — loads prior learnings and "
        "active run state\n"
        "2. **Decompose**: use GPT's chain-of-thought to break tasks before acting\n"
        "3. **Delegate**: use focused subagents for bounded implementation tasks\n"
        "4. **Verify**: run tests after each change — fix failures before moving on\n"
        "5. **Learn**: call `trw_learn()` for reusable gotchas or patterns\n"
        "6. **Finish**: call `trw_deliver()` — persists work for future sessions\n"
        "\n"
        "## Ceremony Protocol\n"
        "\n"
        "- `trw_session_start()` — **first action** in every session\n"
        "- `trw_checkpoint(message)` — after phase transitions; resume point if session ends\n"
        "- `trw_learn(summary, detail)` — records discoveries for all future sessions\n"
        "- `trw_build_check()` — at VALIDATE phase before marking work complete\n"
        "- `trw_deliver()` — **last action**; persists learnings and syncs instruction file\n"
        "\n"
        "## Reasoning Patterns\n"
        "\n"
        "GPT models respond well to explicit chain-of-thought framing:\n"
        "- State the problem and constraints before proposing a solution\n"
        "- For o3/o1 models, the model reasons internally — provide clear goals, "
        "not step-by-step instructions\n"
        "- For gpt-4o/5.x, explicit step-by-step instructions improve output quality\n"
        "- Use `trw_recall(query)` before designing solutions — prior agents may "
        "have already solved the pattern\n"
        "\n"
        "## Structured Output Conventions\n"
        "\n"
        "- Use structured JSON mode for typed outputs when available\n"
        "- Prefer typed Pydantic model arguments in tool calls\n"
        "- Validate outputs against schema before processing downstream\n"
        "- Use system message conventions: role-level context in system, "
        "task-specific context in user turn\n"
        "\n"
        "## Tool-Use Best Practices\n"
        "\n"
        "- Issue TRW tool calls in parallel where independent "
        "(e.g., `trw_recall` + file reads can run together)\n"
        "- `trw_prd_validate()` is required before marking PRD work as implemented\n"
        "- Use `trw_build_check(scope='full')` at VALIDATE, not just at delivery\n"
        "- For multi-PRD sprints, prefer `trw_init()` → run-scoped checkpointing\n"
        "\n"
        "## Known Limitations\n"
        "\n"
        "- **o3/o1 reasoning budget**: these models use internal reasoning tokens; "
        "verbose step-by-step prompts waste budget — provide goals, not procedures\n"
        "- **Tool call ordering**: GPT may try to do everything in one pass; "
        "prompt it to checkpoint at milestones explicitly\n"
        "- **Context window vs. quality**: larger context does not guarantee better "
        "output — targeted, scoped prompts outperform context-dump approaches\n"
        "\n"
        "## Framework Reference\n"
        "\n"
        "Read `.trw/frameworks/FRAMEWORK.md` at session start — it defines the "
        "6-phase execution model, exit criteria, and quality rubrics.\n"
    )


def render_claude() -> str:
    """Render OpenCode instructions optimised for Claude (Anthropic API).

    Context: 200K, extended thinking, XML tags, full ceremony similar to Claude Code.
    """
    return (
        "# Claude TRW Instructions\n"
        "\n"
        "## Context Budget\n"
        "\n"
        "Claude models have a **200K context window**. Leverage the full budget "
        "for codebase understanding. Use extended thinking for complex architectural "
        "decisions. Call `trw_checkpoint()` at phase transitions so the session "
        "can be resumed after context compaction.\n"
        "\n"
        "## Workflow\n"
        "\n"
        "1. **Start**: call `trw_session_start()` — loads prior learnings and "
        "any active run state\n"
        "2. **Assess**: determine task scope and decide whether to self-implement "
        "or delegate to subagents\n"
        "3. **Implement**: use focused subagents for tasks spanning 4+ files\n"
        "4. **Verify**: run tests after each change — fix failures before moving on\n"
        "5. **Learn**: call `trw_learn()` for gotchas, patterns, architectural decisions\n"
        "6. **Finish**: call `trw_deliver()` — persists work for future sessions\n"
        "\n"
        "## Ceremony Protocol\n"
        "\n"
        "- `trw_session_start()` — **first action**; loads accumulated team knowledge\n"
        "- `trw_checkpoint(message)` — after milestones; resume point after compaction\n"
        "- `trw_learn(summary, detail)` — on discoveries; compounds across sessions\n"
        "- `trw_recall(query)` — before designing solutions; prior agents found gotchas\n"
        "- `trw_build_check()` — at VALIDATE and before DELIVER\n"
        "- `trw_deliver()` — **last action**; without this, session discoveries are lost\n"
        "\n"
        "## Reasoning Patterns\n"
        "\n"
        "Claude supports extended thinking for complex reasoning:\n"
        "- Enable extended thinking for: architectural decisions, root-cause analysis, "
        "multi-constraint optimisation\n"
        "- Use XML tags to structure complex prompts: "
        "`<task>`, `<context>`, `<constraints>`, `<output_format>`\n"
        "- Claude excels at reading and navigating codebases — provide file paths, "
        "not file contents, when possible\n"
        "- Leverage `trw_recall()` to load relevant learnings into context rather "
        "than re-reading source files for known patterns\n"
        "\n"
        "## Structured Output Conventions\n"
        "\n"
        "- Use `tool_use` format for structured MCP tool invocations\n"
        "- XML tags improve instruction adherence: wrap constraints in `<constraints>`\n"
        "- Prefer Pydantic v2 model arguments over raw dicts in tool calls\n"
        "- `use_enum_values=True` required on models for YAML round-trip serialization\n"
        "\n"
        "## Tool-Use Best Practices\n"
        "\n"
        "- `trw_prd_validate()` is mandatory before marking PRD work implemented\n"
        "- Parallel tool calls are safe with Claude — batch independent reads\n"
        "- `trw_review()` before delivery for sprint-scale work\n"
        "- Escalate to `trw_init()` for multi-PRD runs requiring phase tracking\n"
        "\n"
        "## Known Limitations\n"
        "\n"
        "- **Post-compaction ceremony skip**: after context compaction, sessions "
        "consistently skip ceremony — always call `trw_session_start()` explicitly "
        "at the start of every continuation\n"
        "- **Over-implementation**: Claude may implement directly rather than delegate — "
        "follow delegation guidance from FRAMEWORK.md for tasks spanning 4+ files\n"
        "- **structlog convention**: `event=` is a reserved kwarg; use alternative "
        "names in log calls\n"
        "\n"
        "## Framework Reference\n"
        "\n"
        "Read `.trw/frameworks/FRAMEWORK.md` at session start — it defines the "
        "6-phase model, delegation decision tree, and quality rubrics. Re-read "
        "after context compaction.\n"
    )


def render_generic() -> str:
    """Render OpenCode instructions for unknown/generic models.

    Assumes 32K context, minimal ceremony, explicit MCP examples.
    """
    return (
        "# TRW Instructions\n"
        "\n"
        "## Context Budget\n"
        "\n"
        "Assuming a **32K context window** (unknown model). Keep instructions "
        "concise and tasks bounded (1-3 files per task). Reference files by path "
        "rather than pasting content inline.\n"
        "\n"
        "## Workflow\n"
        "\n"
        "1. **Start**: call `trw_session_start()` — loads prior learnings\n"
        "2. **Keep tasks bounded**: 1-3 files per task\n"
        "3. **Verify**: run tests after each change — fix failures before moving on\n"
        "4. **Learn**: call `trw_learn()` when you discover a gotcha or pattern\n"
        "5. **Finish**: call `trw_deliver()` — persists work for future sessions\n"
        "\n"
        "## TRW MCP Tools\n"
        "\n"
        "The following tools are available via MCP when the TRW server is configured:\n"
        "\n"
        "```\n"
        "trw_session_start()          — first action; loads prior learnings\n"
        "trw_checkpoint(message)      — save progress at milestones\n"
        "trw_learn(summary, detail)   — record discoveries for future sessions\n"
        "trw_recall(query)            — retrieve relevant learnings\n"
        "trw_build_check()            — run lint, type-check, tests\n"
        "trw_deliver()                — last action; persists everything\n"
        "```\n"
        "\n"
        "## Structured Output Conventions\n"
        "\n"
        "- Issue direct tool calls with explicit, typed arguments\n"
        "- Use explicit file paths — never assume current working directory\n"
        "- Validate tool call results before proceeding to the next step\n"
        "\n"
        "## Tool-Use Best Practices\n"
        "\n"
        "- Call `trw_recall(query)` before re-implementing known patterns\n"
        "- Call `trw_build_check()` to verify your work before delivery\n"
        "- Issue tool calls one at a time if the model has parallel-call limitations\n"
        "\n"
        "## Known Limitations\n"
        "\n"
        "- **Unknown model capabilities**: test delegation patterns to understand "
        "model strengths before relying on them\n"
        "- **32K assumed budget**: if your model has a larger window, you can "
        "include more context per task\n"
        "- **Ceremony compliance**: models without explicit instruction-following "
        "training may skip ceremony; include explicit tool-call examples\n"
        "\n"
        "## Framework Reference\n"
        "\n"
        "Read `.trw/frameworks/FRAMEWORK.md` at session start — it defines the "
        "methodology your tools implement.\n"
    )


def render_opencode_instructions(model_family: str) -> str:
    """Render instructions content for OpenCode .opencode/INSTRUCTIONS.md.

    Produces materially different content for each model family so that
    context budget, reasoning syntax, tool-use patterns, and known
    limitations are appropriate for the detected model.

    Args:
        model_family: One of 'qwen', 'gpt', 'claude', or 'generic'.

    Returns:
        Markdown string for OpenCode-specific instructions.
    """
    if model_family == "qwen":
        return render_qwen()
    if model_family == "gpt":
        return render_gpt()
    if model_family == "claude":
        return render_claude()
    return render_generic()
