"""The single guarded write seam for user-authored instruction files (PRD-FIX-123).

Every writer of a repo-root ``CLAUDE.md`` / ``AGENTS.md`` — the merge writer, the
five bootstrap writers, and the two force branches — calls
:func:`guarded_instruction_write` instead of writing. This module is therefore
the one place the data-loss invariant is expressed, which is what makes the FR06
totality test meaningful and what gives PRD-CORE-243's writer unification a
contract to preserve.

The invariant: **no write may reduce the non-generated byte count of a user's
instruction file without an explicit ``force`` argument.** The incident that
motivated it GREW the target from 2790 to 10403 bytes while destroying 128
hand-written lines, so a total-size floor alone cannot see it (PRD-FIX-123-FR02).

Posture is fail-CLOSED and deliberately inverts this subsystem's fail-open
convention: an unreadable target, an unwritable backup directory, or a backup
path that escapes the project root REFUSES the write. A degraded instruction
file is recoverable; destroyed user content is not (PRD-FIX-123-NFR02).
"""

from __future__ import annotations

import functools
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from contextvars import ContextVar
from dataclasses import dataclass
from pathlib import Path
from typing import ParamSpec, TypeVar

import structlog

from trw_mcp.exceptions import StateError
from trw_mcp.models.config import TRWConfig, get_config
from trw_mcp.models.typed_dicts._ceremony import (
    InstructionDiffDict,
    InstructionWriteRefusalDict,
    InstructionWriteTrigger,
)
from trw_mcp.state.claude_md._marker_layout import ambiguous_marker_refusal
from trw_mcp.state.claude_md._parser import TRW_MARKER_END, TRW_MARKER_START
from trw_mcp.state.claude_md._write_backup import BackupRefused
from trw_mcp.state.claude_md._write_measure import (
    build_diff,
    build_refusal,
    evaluate_floors,
    non_generated_bytes,
    warn_prior_truncation,
)

logger = structlog.get_logger(__name__)

_P = ParamSpec("_P")
_R = TypeVar("_R")

#: Provenance supplied by the entry point (never inferred from a stack walk).
#: A ContextVar rather than a parameter on nine writer signatures: the entry
#: point still SUPPLIES the value, and the seam's interface stays narrow.
_TRIGGER: ContextVar[tuple[InstructionWriteTrigger, str]] = ContextVar(
    "trw_instruction_write_trigger", default=("unknown", "")
)


@contextmanager
def instruction_write_trigger(trigger: InstructionWriteTrigger, caller_tool: str) -> Iterator[None]:
    """Declare what triggered every guarded write inside this block (FR05)."""
    token = _TRIGGER.set((trigger, caller_tool))
    try:
        yield
    finally:
        _TRIGGER.reset(token)


def with_instruction_write_trigger(
    trigger: InstructionWriteTrigger, caller_tool: str
) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]:
    """Decorator form of :func:`instruction_write_trigger`.

    Used where the entry point is a long function whose provenance must hold for
    every write it makes (``init_project`` / ``update_project``) — declaring it
    on the definition keeps the trigger attached to the entry point for EVERY
    caller, not only the CLI dispatcher.
    """

    def decorate(fn: Callable[_P, _R]) -> Callable[_P, _R]:
        @functools.wraps(fn)
        def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> _R:
            with instruction_write_trigger(trigger, caller_tool):
                return fn(*args, **kwargs)

        # functools.wraps copies __name__/__module__/__doc__/__wrapped__, but
        # CPython's inspect.getfile()/getsourcefile() read __code__.co_filename
        # directly and never follow __wrapped__ (a documented stdlib gap — see
        # cpython/inspect.py:getfile). Without this, every tool that reports
        # "where is init_project defined" (doctor checks, error tracebacks
        # pointing a user at source, `inspect.getsource`) points at this guard
        # module instead of the real entry point. Rebinding __code__'s filename
        # and line number to the wrapped function is safe: it only changes
        # introspection metadata, not the bytecode wrapper() executes.
        wrapper.__code__ = wrapper.__code__.replace(  # type: ignore[attr-defined]
            co_filename=fn.__code__.co_filename,
            co_firstlineno=fn.__code__.co_firstlineno,
        )
        return wrapper

    return decorate


@dataclass(frozen=True)
class InstructionWriteVerdict:
    """What the guard did with one candidate.

    Exactly one of the three outcomes holds: ``written`` (the bytes landed),
    ``refusal is not None`` (policy refusal, target byte-identical), or a
    dry-run ``diff`` (nothing written). ``written`` and ``refusal`` are never
    both truthy — PRD-FIX-123-NFR04's mutual-exclusion property.
    """

    written: bool
    total_lines: int = 0
    refusal: InstructionWriteRefusalDict | None = None
    diff: InstructionDiffDict | None = None
    backup_path: str | None = None


def _read_current(target: Path) -> str | None:
    """Return the target's current text, or ``None`` when it does not exist.

    Raises:
        BackupRefused: an existing-but-unreadable target. Fail-closed: the guard
            cannot measure what it would destroy, so it must not write.
    """
    if not target.is_file():
        return None
    try:
        from trw_mcp.state.claude_md._exact_text import read_exact

        return read_exact(target)
    except (OSError, UnicodeDecodeError) as exc:
        raise BackupRefused("unreadable_target", f"could not read {target}: {exc}") from exc


def guarded_instruction_write(
    target: Path,
    candidate: str,
    *,
    markers: tuple[str, str] = (TRW_MARKER_START, TRW_MARKER_END),
    max_lines: int | None = None,
    force: bool = False,
    dry_run: bool = False,
    enforce_shrink_floor: bool = True,
    config: TRWConfig | None = None,
    project_root: Path | None = None,
    expected_current: str | None = None,
) -> InstructionWriteVerdict:
    """Write *candidate* to *target* only if it destroys no user-authored content.

    Args:
        target: The instruction file being written.
        candidate: The full content the caller wants on disk.
        markers: The caller's TRW marker pair, used to locate the generated span.
        max_lines: Line ceiling for the merged result, or ``None`` for writers
            that declare no ceiling. Overflow is REFUSED, never truncated (FR01).
        force: Bypass both shrink floors. A call argument only — never a config
            field, because a switch that re-enables destroying user content is
            the wrong artifact to ship.
        dry_run: Produce a unified diff and write nothing (FR03).
        enforce_shrink_floor: ``False`` for wholly TRW-owned managed files (e.g.
            ``.opencode/INSTRUCTIONS.md``), which carry no user content; backup
            and provenance still apply.
        config: Active configuration; resolved from ``get_config()`` when absent.
        project_root: Root used to contain the backup directory; resolved from
            ``state._paths`` when absent.
        expected_current: The text the caller built *candidate* from. A file that no longer holds it changed
            after the caller read it, and is left as found (CLAUDE-MD S1 codex r1: a stale candidate must never
            overwrite a concurrent save). Independently, the file is re-read right before the publish, which
            itself never replaces a save made at any later point.

    Returns:
        A :class:`InstructionWriteVerdict`. On refusal the target is
        byte-identical to its pre-call content.
    """
    cfg = config if config is not None else get_config()
    if project_root is None:
        from trw_mcp.state import _paths

        project_root = _paths.resolve_project_root()

    try:
        current = _read_current(target)
    except BackupRefused as exc:
        return InstructionWriteVerdict(
            written=False,
            refusal=build_refusal(target, "unreadable_target", exc.detail, lines=0, limit=0, counts=(0, 0, 0, 0)),
        )

    if expected_current is not None and current != expected_current:
        return InstructionWriteVerdict(
            written=False,
            refusal=build_refusal(
                target,
                "changed_since_read",
                "the file changed after TRW read it; left as found, run the command again",
                lines=0,
                limit=0,
                counts=(0, 0, 0, 0),
            ),
        )

    if (
        current is not None
        and enforce_shrink_floor
        and (ambiguous := ambiguous_marker_refusal(target, current, markers))
    ):
        return InstructionWriteVerdict(written=False, refusal=ambiguous)

    if current is not None:
        warn_prior_truncation(target, current)

    current_total = len(current.encode("utf-8")) if current is not None else 0
    candidate_total = len(candidate.encode("utf-8"))
    current_ng = non_generated_bytes(current, markers) if current is not None else 0
    candidate_ng = non_generated_bytes(candidate, markers)
    counts = (current_ng, candidate_ng, current_total, candidate_total)
    candidate_lines = len(candidate.split("\n"))

    refusal = evaluate_floors(
        target,
        counts=counts,
        candidate_lines=candidate_lines,
        max_lines=max_lines,
        force=force,
        enforce_shrink_floor=enforce_shrink_floor,
        shrink_fraction=cfg.instruction_write_max_total_shrink_fraction,
        block_delta_tolerance_bytes=cfg.instruction_write_block_delta_tolerance_bytes,
        current=current,
        candidate=candidate,
        markers=markers,
    )
    if refusal is not None:
        return InstructionWriteVerdict(written=False, refusal=refusal)

    if dry_run:
        diff = build_diff(target, current or "", candidate, cfg.instruction_dry_run_diff_max_lines)
        return InstructionWriteVerdict(written=False, total_lines=candidate_lines, diff=diff)

    backup_path: str | None = None
    if current != candidate:  # a byte-identical rewrite writes nothing and takes no backup (NFR02 idempotence)
        from trw_mcp.state.claude_md._publish import publish
        from trw_mcp.state.claude_md._write_backup import prepare_backup_dir

        directory: Path | None = None
        if current is not None:
            try:  # fail-closed: no write without a contained, existing backup directory
                directory = prepare_backup_dir(project_root, cfg.instruction_backup_dir)
            except BackupRefused as exc:
                logger.warning(
                    "instruction_write_backup_refused", path=str(target), reason=exc.reason, detail=exc.detail
                )
                return InstructionWriteVerdict(
                    written=False,
                    refusal=build_refusal(
                        target, exc.reason, exc.detail, lines=candidate_lines, limit=max_lines or 0, counts=counts
                    ),
                )
        try:
            still = _read_current(target)
        except BackupRefused as exc:
            still = exc.detail  # unreadable now: never equal to *current*, so the write is refused below
        if still != current:
            return InstructionWriteVerdict(
                written=False,
                refusal=build_refusal(
                    target,
                    "changed_during_write",
                    "the file changed while TRW was writing it; left as found, run the command again",
                    lines=candidate_lines,
                    limit=max_lines or 0,
                    counts=counts,
                ),
            )
        try:
            # Never a compare-then-replace: the file is captured and re-proven, the new bytes are linked in, and the
            # displaced file becomes the backup by rename (PUBLISH-RACE-HARDEN; see _publish).
            published = publish(target, project_root, candidate, current, directory, cfg.instruction_backup_retention)
        except (StateError, OSError) as exc:
            return InstructionWriteVerdict(
                written=False,
                refusal=build_refusal(
                    target, "write_failed", str(exc), lines=candidate_lines, limit=max_lines or 0, counts=counts
                ),
            )
        if published.blocked is not None:
            return InstructionWriteVerdict(
                written=False,
                refusal=build_refusal(
                    target,
                    "write_failed" if published.failed else "changed_during_write",
                    published.blocked,
                    lines=candidate_lines,
                    limit=max_lines or 0,
                    counts=counts,
                ),
            )
        backup_path = str(published.backup) if published.backup is not None else None

    trigger, caller_tool = _TRIGGER.get()
    # info, not debug: debug is dropped entirely under the shipped default level,
    # so a debug-level provenance record would not exist for the operator asking
    # "what changed my instruction file?" (FR05).
    logger.info(
        "instruction_write_provenance",
        path=str(target),
        trigger=trigger,
        caller_tool=caller_tool,
        byte_delta=candidate_total - current_total,
    )
    if force and current is not None:
        logger.warning(
            "instruction_write_forced",
            path=str(target),
            non_generated_byte_delta=candidate_ng - current_ng,
            total_byte_delta=candidate_total - current_total,
        )
    return InstructionWriteVerdict(written=True, total_lines=candidate_lines, backup_path=backup_path)


__all__ = [
    "InstructionWriteVerdict",
    "guarded_instruction_write",
    "instruction_write_trigger",
    "non_generated_bytes",
    "with_instruction_write_trigger",
]
