"""One-line descriptions for the TRWConfig fields whose declaration carries none (`trw-mcp config-reference`).

The declarations in ``_fields_*.py`` are plain annotated attributes; the text lives here so a domain mixin file does not
grow past its line ceiling. ``apply_descriptions`` copies each entry onto the field's ``description`` when
``_main_fields`` assembles the config class and to ``TRWConfig`` itself, so ``model_fields`` and the reference see it (the
cached JSON schema is not rebuilt for it).
``tests/test_config_field_descriptions.py`` fails when a field has no description in either place.
"""

from __future__ import annotations

from typing import Any

FIELD_DESCRIPTIONS: dict[str, str] = {
    "meta_tune": "Nested meta-tuning settings (`meta_tune.enabled` mirrors `meta_tune_enabled`).",
    "security": "Nested security settings for the MCP trust boundary.",
    "aaref_version": "AARE-F requirements-framework version stamp deployed with the project.",
    "access_count_utility_boost_cap": "Largest utility bonus a learning can earn from being recalled often.",
    "additional_repo_roots": "Sibling repository roots for multi-repo workspaces, so PRD key-file references into sibling repos resolve instead of failing as missing paths.",
    "agent_report_max_chars": "Character limit each bundled agent is asked to keep its final report within (guidance to the model); 0 renders no limit.",
    "agents_enabled": "Install bundled sub-agent definitions; unset follows the client profile.",
    "agents_md_enabled": "Write TRW's block into `AGENTS.md`.",
    "ambiguity_rate_max": "Highest allowed share of ambiguous terms in a PRD (0-1).",
    "assertion_failure_penalty": "Recall-rank penalty (0-1) for a learning whose stored assertions fail verification, scaled by the failing fraction.",
    "assertion_stale_threshold_days": "Days after which a learning's assertion verification is stale and due for re-verification.",
    "auto_checkpoint_pre_compact": "Write a checkpoint automatically before the client compacts context.",
    "auto_recall_enabled": "Let the prompt hook inject relevant learnings before each prompt (the master `learning_recall_enabled` switch outranks it).",
    "auto_recall_max_results": "Most learnings the prompt hook injects per prompt.",
    "auto_recall_max_tokens": "Token budget for the learnings the prompt hook injects per prompt.",
    "auto_recall_min_score": "Minimum relevance (0-1, IDF-weighted share of prompt keywords a learning covers) a learning needs to be injected by the prompt hook.",
    "auto_recall_scan_cap": "Most stored learnings the prompt hook's auto-recall scorer scans per prompt (0 or a small value scores only a recent window).",
    "backend_api_key": "API key for the sync backend; empty means none configured.",
    "backend_url": "Base URL of the sync backend; empty means no backend configured.",
    "backup_remote_enabled": "Allow uploading a backup archive of the local store to the platform; off by default because the archive is the raw local store.",
    "build_check_coverage_min": "Minimum test coverage percentage a build check must report to pass the build gate.",
    "build_check_enabled": "Run the build-check gate; false turns the build-check requirement off for validation and deliver.",
    "build_gate_enforcement": "How the build gate reacts to a failed check: `strict` blocks, `lenient` warns, `off` ignores it.",
    "ceremony_feedback_escalation_threshold": "Ceremony score below which recent sessions escalate the ceremony level.",
    "ceremony_feedback_escalation_window": "Number of recent sessions considered when deciding to escalate ceremony.",
    "ceremony_feedback_min_samples": "Sessions needed before ceremony feedback adjusts the ceremony level.",
    "ceremony_feedback_quality_threshold": "Outcome quality (0-1) at or above which a session counts as good for feedback.",
    "ceremony_feedback_score_threshold": "Ceremony score at or above which a session counts as well-run for feedback.",
    "ceremony_mode": "Ceremony weight: `full` or `light` (shorter guidance and fewer nudges).",
    "changelog_advisory_enabled": "Warn at deliver when source changed but the package changelog did not; off by default.",
    "code_index_exclude_dirs": "Directory names the code index skips when scanning the project.",
    "code_index_include_extensions": "File extensions the code index includes when scanning the project.",
    "comms_enabled": "Enable the swarm comms tools; they do nothing until a formation is joined.",
    "compact_instructions_template": "Custom text for the instructions preserved across context compaction; empty uses the built-in template.",
    "completeness_min": "Lowest allowed PRD completeness score (0-1).",
    "complexity_hard_override_threshold": "Number of active risk signals at which the run is forced to the highest complexity tier regardless of score.",
    "complexity_tier_comprehensive": "Complexity score at or above (this value plus one) that classifies a run as COMPREHENSIVE.",
    "complexity_tier_minimal": "Complexity score at or below which a run is classified MINIMAL.",
    "complexity_weight_architecture_change": "Complexity points added when the task changes architecture.",
    "complexity_weight_cross_cutting": "Complexity points added when the task is cross-cutting.",
    "complexity_weight_external_integration": "Complexity points added when the task integrates an external system.",
    "complexity_weight_files_affected_max": "Cap on the complexity points contributed by the number of files a task affects.",
    "complexity_weight_large_refactoring": "Complexity points added when the task is a large refactoring.",
    "complexity_weight_novel_patterns": "Complexity points added when the task introduces novel patterns.",
    "compliance_changelog_filename": "File name of the project changelog the deliver changelog advisory looks at (default `CHANGELOG.md`).",
    "compliance_dir": "Directory under the TRW state dir that holds compliance records (default `compliance`).",
    "compliance_review_retention_days": "Days automated review records are kept before they may be pruned.",
    "context_dir": "Directory under the TRW state dir that holds live session context files (default `context`).",
    "cross_model_provider": "Dispatch client id (for example `codex`) used for cross-model review; empty means no reviewer.",
    "cross_model_review_enabled": "Ask a second model family for a review of the diff in addition to the local review; off by default.",
    "cross_model_review_timeout_secs": "Seconds to wait for the cross-model reviewer before giving up.",
    "dedup_enabled": "Check a new learning against existing ones and skip or merge near-duplicates.",
    "dedup_merge_threshold": "Similarity (0-1) at or above which a new learning is merged into an existing one.",
    "dedup_skip_threshold": "Similarity (0-1) at or above which a new learning is skipped as a duplicate.",
    "deferred_batch_max_seconds": "Seconds the whole deferred post-deliver batch may run.",
    "deferred_lock_stale_seconds": "Seconds after which a deferred-delivery lock is treated as abandoned and taken over.",
    "deferred_step_max_seconds": "Seconds one deferred post-deliver maintenance step may run before it is abandoned.",
    "deliver_gate_mode": "Deliver gate posture: `advisory` warns only, `block_coding` blocks a missing build check for coding-type tasks, `block_all` blocks for every task type.",
    "deliver_gate_task_type_overrides": 'Per-task-type override of `deliver_gate_mode`, e.g. `{"eval": "advisory"}`; empty by default.',
    "deliver_gate_unclassified_change_threshold": "Number of distinct files a session must modify before the missing-build deliver gate arms for a task type that does not inherently expect a build.",
    "deliver_graph_backfill_deadline_seconds": "Seconds the deliver-time knowledge-graph backfill may run before it stops.",
    "deliver_graph_backfill_enabled": "On deliver, build knowledge-graph edges for not-yet-graphed learnings within a small time budget.",
    "delivery_operations_mode": "Delivery journal mode: `off` disables it, `observe` records without acting, `enforce` acts on it.",
    "density_weight_default": "Weight of any other PRD section in the content-density score.",
    "density_weight_functional_requirements": "Weight of the Functional Requirements section in the content-density score.",
    "density_weight_problem_statement": "Weight of the Problem Statement section in the content-density score.",
    "density_weight_traceability_matrix": "Weight of the Traceability Matrix section in the content-density score.",
    "display_timezone": "IANA timezone used to render local times in `trw_status`; stored and compared times stay UTC.",
    "dry_check_enabled": "Run the duplicate-code (DRY) check in the build gate.",
    "dry_check_min_block_size": "Fewest identical lines that count as a duplicated block in the DRY check.",
    "embeddings_coverage_warn_threshold": "Share (0-1) of learnings without embeddings above which the pipeline-health check warns.",
    "embeddings_enabled": "Use embeddings for hybrid recall; false falls back to keyword search only.",
    "entries_dir": "Directory under the learnings dir that holds individual learning entries (default `entries`).",
    "events_file": "File name of the per-run event log (default `events.jsonl`).",
    "evidence_receipt_mode": "Evidence receipt compatibility: `observe` writes typed receipts alongside the legacy files, `enforce` requires the typed receipts.",
    "factory_enabled": "Enable the experimental software-factory commands (status, receipts, factory checkpoints); off unless you opt in.",
    "feedback": "Settings for the feedback channel behind `trw_status(feedback=...)`.",
    "formation_activity_stall_seconds": "Seconds without activity after which a formation member is reported as stalled.",
    "formation_deliver_gate": "Whether delivering while a joined formation member is mid-work blocks (`block`) or only warns (`advisory`).",
    "formation_hook_ownership_mode": "PreToolUse ownership check for formation members: `warn` reports an unowned edit, `off` disables it (never blocks).",
    "formation_ownership_enforcement": "Commit-boundary check that a member only commits paths it owns: `refuse` blocks the commit, `warn` only reports it.",
    "framework_md_enabled": "Deploy the framework document into the project; unset follows the client profile.",
    "framework_version": "Framework version stamp deployed with the project (managed by `make framework-bump`, not by hand).",
    "frameworks_dir": "Directory under the TRW state dir where the deployed framework documents live (default `frameworks`).",
    "hint_hub_downrank": "On a hub file (more anchored lessons than `hint_hub_threshold`), list anchor-only lessons after the text-matched ones; false restores anchored-first ordering.",
    "hint_sidecar_ancestor_enabled": "Let the pre-edit hint use a proven-ancestor commit's sidecar when the exact-HEAD one is missing, instead of no sidecar half at all.",
    "hint_sidecar_auto_refresh_enabled": "Pre-edit hint spawns a sidecar rebuild itself when the current one is missing or stale (the post-commit refresh alone did not land one in time).",
    "hint_sidecar_refresh_enabled": "Post-commit hook requests a detached rebuild of the trw-distill pre-edit-hint sidecar and refreshes the risk report; false stops the refresh.",
    "hooks_enabled": "Master switch for every bundled hook; false disables them all.",
    "hybrid_rrf_k": "Reciprocal-rank-fusion constant used to merge keyword and vector recall rankings.",
    "impact_forced_distribution_enabled": "Cap how many new learnings can be rated critical or high so impact scores stay meaningful.",
    "impact_high_threshold_pct": "Largest percentage of active learnings allowed at impact 0.8 or above; a new high-impact learning that would exceed it is lowered.",
    "impact_tier_critical_cap": "Largest share (0-1) of learnings that may be in the critical impact tier.",
    "impact_tier_high_cap": "Largest share (0-1) of learnings that may be in the high impact tier.",
    "index_auto_sync_on_status_change": "Regenerate the PRD index automatically when a PRD's status changes.",
    "installation_id": "Explicit installation identifier; empty derives a stable `inst-<hash>` from the project root path.",
    "instruction_backup_dir": "Project-relative directory where instruction-file backups are written before a guarded rewrite.",
    "instruction_size_gate_mode": "Whether an over-size TRW instruction block only warns (`warn`) or is refused (`block`); unset lets the client profile decide.",
    "intel_cache_enabled": "Cache fetched intelligence payloads locally for `intel_cache_ttl_seconds`.",
    "intel_cache_ttl_seconds": "Seconds a fetched intelligence payload stays cached before it is refetched.",
    "knowledge_jaccard_threshold": "Tag-overlap (Jaccard) similarity at which two learnings are linked in the knowledge topology.",
    "knowledge_min_cluster_size": "Fewest learnings a topic cluster needs to be written out.",
    "knowledge_output_dir": "Directory under the TRW state dir where knowledge-topology pages are written (default `knowledge`).",
    "knowledge_sync_threshold": "Number of new learnings that triggers a knowledge-topology rebuild.",
    "learn_journal_drain_budget_ms": "Milliseconds a session-start learn-journal sweep may spend replaying before it stops and leaves the rest.",
    "learn_journal_drain_limit": "Most pending learn-journal records replayed per session-start sweep; the rest drain on later sweeps.",
    "learn_journal_enabled": "Durably journal an accepted `trw_learn` before the slow store pipeline so a crash mid-write loses nothing; replayed at the next session start.",
    "learn_journal_max_replay_attempts": "Replay attempts before a record that keeps failing transiently is dead-lettered instead of retried forever.",
    "learning_auto_prune_cap": "Active learnings kept by the auto-prune pass; lowest-value ones beyond it are pruned.",
    "learning_auto_prune_max_seconds": "Wall-clock budget in seconds for one auto-prune pass; a pass that hits it returns the partial result.",
    "learning_auto_prune_min_interval_hours": "Least hours between two auto-prune passes (a pass is expensive on large stores).",
    "learning_auto_prune_on_deliver": "Prune low-value learnings automatically after deliver.",
    "learning_decay_half_life_days": "Days for a learning's utility to halve when unused.",
    "learning_decay_use_exponent": "Exponent applied to use count when slowing a learning's decay.",
    "learning_max_entries": "Most learnings kept in the store; the lowest-value ones beyond it are dropped by maintenance.",
    "learning_outcome_correlation_scope": "Which recalls an outcome is attributed to: `session` or a wider scope.",
    "learning_outcome_correlation_window_minutes": "Minutes after a recall within which a build outcome is attributed to the learnings shown.",
    "learning_promotion_impact": "Impact score (0-1) at or above which a learning is promoted into the instruction file.",
    "learning_recall_enabled": "Master switch for learnings reaching the agent through recall, hints and hooks; false keeps them all off.",
    "learning_repeated_op_threshold": "Times the same operation must recur before it is suggested as a learning.",
    "learning_sharing_enabled": "Separate consent to publish learning content (summary and detail) to the platform; off by default and distinct from usage telemetry.",
    "learning_utility_delete_threshold": "Utility below which a learning is deleted outright.",
    "learning_utility_prune_threshold": "Utility below which a learning becomes a prune candidate.",
    "learnings_dir": "Directory under the TRW state dir that holds learnings (default `learnings`).",
    "llm_default_model": "Model alias used for TRW's own small LLM calls (default `haiku`).",
    "llm_usage_log_enabled": "Log every TRW LLM call's usage to `llm_usage_log_file`.",
    "llm_usage_log_file": "File name of the LLM usage log (default `llm_usage.jsonl`).",
    "logs_dir": "Directory under the TRW state dir that holds log and usage files (default `logs`).",
    "max_auto_lines": "Line limit for the whole instruction file after TRW's block is merged in; a write that would exceed it is refused, never truncated.",
    "max_consolidated_tags": "Most tags kept on a consolidated (merged) learning.",
    "memory_cold_threshold_days": "Days without use after which a low-importance entry is archived to the cold tier.",
    "memory_consolidation_enabled": "Run periodic consolidation that merges clusters of similar learnings.",
    "memory_consolidation_max_per_cycle": "Most learnings consolidated in one cycle.",
    "memory_consolidation_min_cluster": "Fewest similar learnings that form a cluster worth consolidating.",
    "memory_consolidation_similarity_threshold": "Similarity (0-1) two learnings need to be clustered for consolidation.",
    "memory_hot_max_entries": "Most entries kept in the hot memory tier before the oldest move to warm.",
    "memory_hot_ttl_days": "Days an entry stays in the hot tier before it moves to warm.",
    "memory_retention_days": "Days after which an unused low-importance entry may be purged.",
    "memory_score_w1": "Weight of query relevance in a learning's composite score (the three weights are normalized to sum to 1).",
    "memory_score_w2": "Weight of recency (decays with days since last access) in a learning's composite score.",
    "memory_score_w3": "Weight of the learning's impact rating in its composite score.",
    "meta_tune_enabled": "Enable the meta-tuning loop (self-modification sandbox); off by default and only supported on Linux.",
    "migration_gate_enabled": "Run the database-migration check in the build gate.",
    "nudge_budget_chars": "Character budget for the nudge text added to one tool response.",
    "nudge_enabled": "Show ceremony nudges to the agent; unset follows the client profile.",
    "nudge_messenger": "Nudge wording variant (`standard`, `minimal`, `contextual`, ...); unset follows the client profile.",
    "nudge_pool_cooldown_after": "Times a pooled nudge may show before it goes on cooldown.",
    "nudge_pool_cooldown_calls": "Tool calls a pooled nudge stays silent once it is on cooldown.",
    "nudge_variant": "Label stamped on nudge events to compare arms in live traffic; routing still follows `nudge_messenger`.",
    "otel_enabled": "Set up OpenTelemetry tracing at startup; off by default.",
    "parallelism_max": "Parallelism ceiling written into a new project's `config.yaml` at init (default 10).",
    "patterns_dir": "Directory under the TRW state dir that holds recorded patterns (default `patterns`).",
    "phase_gate_enforcement": "How phase-exit gates react to unmet criteria: `strict` blocks, `lenient` warns, `off` ignores.",
    "platform_api_key": "API key for the TRW platform (kept secret in output); empty means none configured.",
    "platform_contact_enabled": "Master veto on every network call to the TRW platform (sync, backup, telemetry uploads); false keeps the install fully offline.",
    "platform_telemetry_enabled": "Send anonymous usage telemetry to the TRW platform; off by default and separate from learning sharing.",
    "platform_url": "Base URL of the TRW platform this install talks to; empty means none configured.",
    "platform_urls": "Ordered list of platform URLs; the first is used and the rest are fallbacks.",
    "post_commit_distill_incremental": "Let the post-commit hook run `trw-distill run --incremental --live-ingest`, which may call an LLM and writes lessons into the store; off unless you choose it.",
    "prd_min_content_density": "Least content density a PRD needs to move from DRAFT to REVIEW.",
    "prd_required_status_for_implement": "PRD status required before the implement phase may start (default `approved`).",
    "prd_transition_gate": "Whether moving a PRD to implemented without accepted evidence only warns (`warn`) or is blocked (`block`).",
    "prds_relative_path": "Project-relative directory that holds PRD documents (default `docs/requirements-aare-f/prds`).",
    "pricing_table_path": "Path to a custom model pricing table for cost estimates; empty uses the bundled one.",
    "profile_system_enabled": "Resolve and apply the layered client/domain profile at session start; false skips profile resolution.",
    "project_namespace": "Stable memory-store namespace for this project once migrated to the machine-local daemon store; empty means the checkout keeps its own `.trw/memory` store.",
    "recall_internal_fields": "Learning fields removed from recall results because they are internal.",
    "recall_max_results": "Most learnings `trw_recall` returns for one query.",
    "recall_provenance_inline": "Show source and scope inline in each recalled learning stub so provenance is checked before a claim is reused.",
    "recall_utility_lambda": "Weight of utility in targeted recall ranking; 0 disables utility preferences (query relevance always wins).",
    "receipts_dir": "Directory under the TRW state dir that holds build/review receipts (default `receipts`).",
    "reflect_max_success_patterns": "Most success patterns kept per reflection.",
    "reflections_dir": "Directory under the TRW state dir that holds reflection outputs (default `reflections`).",
    "requirement_drift_gate": "Deliver-time requirement-drift gate: `warn` or `block`; unset keeps the per-PRD default (block for safety-critical PRDs, warn otherwise).",
    "response_format": "Format of tool responses: `yaml` or `json`.",
    "reversion_rate_concerning": "Phase-reversion rate (0-1) above which the reversion rate is reported as concerning.",
    "reversion_rate_elevated": "Phase-reversion rate (0-1) above which the reversion rate is reported as elevated.",
    "review_confidence_threshold": "Minimum finding confidence (0-100) for an automated review finding to be reported.",
    "review_gate_mode": "Whether a STANDARD or COMPREHENSIVE run that reaches deliver with no recorded review only warns (`warn`) or is blocked (`block`).",
    "review_mandate_advisory_enabled": "Tell the agent up front that STANDARD and COMPREHENSIVE runs need a review before deliver (advisory only).",
    "review_verdict_ttl_hours": "Hours a recorded review verdict stays valid at deliver time; older ones are treated as expired even if the reviewed bytes did not move.",
    "risk_scaling_enabled": "Scale PRD validation thresholds by the PRD's risk level.",
    "run_auto_close_enabled": "Close stale runs automatically when run status is assembled.",
    "run_stale_ttl_hours": "Hours without activity after which a run counts as stale and may be auto-closed.",
    "runs_root": "Project-relative directory where run directories are created (default `.trw/runs`).",
    "scoring_default_days_unused": "Days-unused value assumed for a learning with no recorded last use.",
    "scripts_dir": "Directory under the TRW state dir that holds generated helper scripts (default `scripts`).",
    "self_review_blocking": "Make the self-review hook block instead of only reminding.",
    "semantic_checks_enabled": "Run semantic checks in the build gate in addition to syntax checks.",
    "session_start_recall_enabled": "Recall learnings at session start; unset follows `learning_recall_enabled`.",
    "shared_mcp": "Opt-in shared MCP server settings: `enabled` makes clients launch `trw-mcp-proxy` against one shared server instead of one stdio server each.",
    "skills_enabled": "Install bundled skills; unset follows the client profile.",
    "source_human_utility_boost": "Utility bonus for learnings a human wrote or confirmed.",
    "sub_claude_md_max_lines": "Line limit for a module-level (sub-scope) instruction file.",
    "surface_role": "MCP surface role: `agent` is the normal full surface, `reviewer` a read-only report surface for dispatched review sessions (normally set by the environment, not here).",
    "sync_interval_seconds": "Seconds between team-sync push/pull cycles.",
    "sync_pull_timeout_seconds": "Seconds to wait for a pull request before giving up.",
    "sync_push_batch_size": "Most learnings pushed to the backend in one batch.",
    "sync_push_timeout_seconds": "Seconds to wait for a push request before giving up.",
    "task_root": "Project-relative directory that holds task directories (default `docs`).",
    "team_sync_enabled": "Enable team sync of learnings with the backend; off by default.",
    "telemetry": "Legacy usage-telemetry switch copied into a new project's `config.yaml` at init; the live switch is `telemetry_enabled`.",
    "telemetry_enabled": "Record local tool-call telemetry under the logs directory.",
    "telemetry_file": "File name of the local tool-call telemetry log (default `tool-telemetry.jsonl`).",
    "templates_dir": "Directory under the TRW state dir that holds generated templates (default `templates`).",
    "time_tracking_enabled": "Track elapsed time and ETAs for task-scaled runs and show them in `trw_status`, checkpoints and deliver.",
    "timebox_hours": "Default time box in hours written into a new project's `config.yaml` at init (default 8).",
    "tool_resolution_mode": "Which tool packs the MCP server exposes: `standard` is the kernel plus every pack whose flag is on, `all` also enables the comms and assess packs.",
    "traceability_coverage_min": "Lowest allowed share of requirements traced to code or tests (0-1).",
    "transition_nudges_enabled": "Allow phase-transition nudge lines (learning and suggestion lines) to reach the agent; independent of `nudge_enabled`.",
    "trust_crawl_boundary": "Session count up to which an agent stays in the `crawl` trust tier; above it the tier is `walk`.",
    "trust_walk_boundary": "Session count up to which an agent stays in the `walk` trust tier; above it the tier is `run`.",
    "trw_dir": "Name of the TRW state directory inside the project (default `.trw`).",
    "validation_density_weight": "Points a PRD can earn for content density in the validation score.",
    "validation_draft_threshold": "Validation score at or above which a PRD is at least REVIEW quality.",
    "validation_implementation_readiness_weight": "Points a PRD can earn for implementation readiness in the validation score.",
    "validation_review_threshold": "Validation score at or above which a PRD is APPROVED quality.",
    "validation_skeleton_threshold": "Validation score at or above which a PRD is at least DRAFT quality (below it: skeleton).",
    "validation_structure_weight": "Points a PRD can earn for structure in the validation score.",
    "validation_traceability_weight": "Points a PRD can earn for traceability in the validation score.",
    "wiring_gate_mode": "Whether a PRD whose requirements are not wired to code only warns (`warn`) or fails validation (`block`).",
    "wiring_gate_mode_overrides": "Per-PRD override of `wiring_gate_mode` (PRD id or category to `warn`/`block`); empty means every PRD uses the global mode.",
}


def apply_descriptions(model: Any) -> None:
    """Set ``description`` on every field of *model* that has none and has an entry above."""
    for name, field in model.model_fields.items():
        if not (field.description or "").strip() and name in FIELD_DESCRIPTIONS:
            field.description = FIELD_DESCRIPTIONS[name]


__all__ = ["FIELD_DESCRIPTIONS", "apply_descriptions"]
