"""PRD-STATUS-HEADER-SHADOW + PRD-SUPERSEDED-BUCKET: the INDEX projection files each PRD by its own prd.status."""

from __future__ import annotations

from pathlib import Path

_SHADOWED = """---
prd:
  id: PRD-CORE-901
  title: Shadowed status
  status: done
  priority: P1
  category: CORE
### PRD Status Header (auto-generated by system)
status:
  implementation_status: fully_implemented
  implementation_confidence: high
---

# PRD-CORE-901: Shadowed status
"""

_SUPERSEDED = """---
prd:
  id: PRD-CORE-902
  title: Replaced by something else
  status: superseded
  priority: P1
  category: CORE
---

# PRD-CORE-902: Replaced by something else
"""


def _section_of(text: str, prd_id: str) -> str:
    """The ``###`` heading directly above *prd_id*'s row (empty groups render no heading)."""
    heading = ""
    for line in text.splitlines():
        if line.startswith("### "):
            heading = line
        elif line.startswith(f"| {prd_id} |"):
            return heading
    raise AssertionError(f"{prd_id} not rendered")


def _write(root: Path, name: str, text: str) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    (root / name).write_text(text, encoding="utf-8")
    return root


def test_embedded_status_header_mapping_does_not_shadow_prd_status(tmp_path: Path) -> None:
    from trw_mcp.state.index_sync import scan_prd_frontmatters

    prds = _write(tmp_path / "prds", "PRD-CORE-901.md", _SHADOWED)
    [entry] = scan_prd_frontmatters(prds)
    assert entry.status == "done"


def test_shadowed_done_prd_renders_under_done_not_draft(tmp_path: Path) -> None:
    from trw_mcp.state.index_sync import render_index_catalogue, scan_prd_frontmatters

    prds = _write(tmp_path / "prds", "PRD-CORE-901.md", _SHADOWED)
    text = render_index_catalogue(scan_prd_frontmatters(prds))
    assert _section_of(text, "PRD-CORE-901").startswith("### Done (")


def test_superseded_prd_gets_its_own_bucket_not_draft(tmp_path: Path) -> None:
    from trw_mcp.state.index_sync import render_index_catalogue, scan_prd_frontmatters

    prds = _write(tmp_path / "prds", "PRD-CORE-902.md", _SUPERSEDED)
    text = render_index_catalogue(scan_prd_frontmatters(prds))
    assert _section_of(text, "PRD-CORE-902") == "### Superseded (1)"
    assert "1 superseded" in text


def test_superseded_is_terminal_in_the_requirements_registry() -> None:
    from trw_mcp.state import requirements_registry

    assert "superseded" in requirements_registry._TERMINAL_STATUSES


def test_superseded_sorts_with_the_historical_statuses() -> None:
    from trw_mcp.state.index_sync import _STATUS_ORDER

    assert _STATUS_ORDER["superseded"] > _STATUS_ORDER["draft"]


def test_registry_treats_a_shadowed_done_prd_as_terminal(tmp_path: Path) -> None:
    """The requirements registry read the same shadowed status, so a done PRD stayed an executable row."""
    from trw_mcp.state import requirements_registry

    prds = _write(tmp_path / "prds", "PRD-CORE-901.md", _SHADOWED)
    _write(prds, "PRD-CORE-902.md", _SUPERSEDED)
    assert requirements_registry._scan_executable_entries(prds) == []
