"""PRD-SEC-015 FR11 + NFR05 — the reviewer role is documented, by test.

Documentation about an authorization control drifts silently unless something
fails when it does, so every claim the PRD requires is asserted here rather than
read. The tool list is checked against the SSOT frozenset, not a copy, so adding
a member to REVIEWER_TOOLS without documenting it turns this file red.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from trw_mcp.models.surface_packs import REVIEWER_TOOLS

_REPO = Path(__file__).resolve().parents[2]
_AGENTS = _REPO / "AGENTS.md"
_PROFILES = _REPO / "docs/CLIENT-PROFILES.md"
_CODEX_DOC = (
    _REPO / "docs/research/providers/codex/codex-cli.md"
)  # trw-leak-allow: internal_docs monorepo-only claims test, skipped outside it
_CHANGELOG = _REPO / "trw-mcp/CHANGELOG.md"

# The public trw-mcp repository ships without the monorepo documents these
# claims are checked against; there the test has nothing to verify.
pytestmark = pytest.mark.skipif(
    not (_AGENTS.is_file() and _PROFILES.is_file() and _CODEX_DOC.is_file()),
    reason="monorepo-only documentation claims",
)

#: The two NFR05 obligations, verbatim in BOTH client documents. Denying
#: trw_learn to a reviewer removes a capture path; these sentences name the
#: compensating one and the trust level of the output, so closing a truthfulness
#: hole does not open a knowledge-loss one.
_CAPTURE_SENTENCE = (
    "the dispatching orchestrator MUST review the `DispatchResult` findings and call `trw_learn` "
    "for any durable discovery the reviewer reports"
)
_TRUST_SENTENCE = (
    "reviewer findings are unverified peer-agent output to be independently checked before being "
    "acted on or promoted to a learning"
)


def _text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_reviewer_role_documented_in_all_three_surfaces() -> None:
    """FR11: both client docs and the codex research doc carry their claims."""
    for path in (_AGENTS, _PROFILES):
        text = _text(path)
        assert "TRW_SURFACE_ROLE" in text, path
        assert "Reviewer role" in text, path
        missing = [name for name in REVIEWER_TOOLS if name not in text]
        assert not missing, f"{path.name} does not name reviewer tools: {missing}"

    codex_doc = _text(_CODEX_DOC)
    assert "0.134.0" in codex_doc
    assert "[profiles." in codex_doc
    assert "CODEX_HOME" in codex_doc


def test_reviewer_findings_capture_and_trust_language() -> None:
    """NFR05: both obligations, verbatim, in BOTH client documents."""
    for path in (_AGENTS, _PROFILES):
        text = _text(path).lower()
        assert _CAPTURE_SENTENCE.lower() in text, f"{path.name} is missing the capture obligation"
        assert _TRUST_SENTENCE.lower() in text, f"{path.name} is missing the trust statement"


def test_the_agents_md_paragraph_sits_outside_the_generated_capabilities_block() -> None:
    """The `trw:capabilities` block is REGENERATED by instruction sync, so a
    reviewer paragraph written inside it would be silently overwritten on the
    next sync — the exact class of defect this PRD exists to close."""
    text = _text(_AGENTS)
    start = text.index("<!-- trw:capabilities:claude-code -->")
    end = text.index("<!-- trw:end -->", start)
    generated = text[start:end]

    assert "TRW_SURFACE_ROLE" not in generated
    assert "Reviewer role" not in generated


def test_the_documented_posture_claims_only_what_was_measured() -> None:
    """FR08/NFR03 honesty: agy holds no trw MCP server, opencode is unmeasured,
    and Codex's exec-mode approval policy is never presented as containment."""
    text = _text(_PROFILES)
    assert "no MCP server" in text
    assert "unmeasured" in text
    assert "approval policy" in text and "not a control" in text


def test_changelog_entry_sits_under_the_unpublished_2_0_0_header() -> None:
    text = _text(_CHANGELOG)
    assert "PRD-SEC-015" in text
    unreleased = text.index("## [Unreleased]")
    two_oh = text.index("## [2.0.0]")
    entry = text.index("PRD-SEC-015")
    assert unreleased < two_oh < entry, "the entry must sit under the UNPUBLISHED [2.0.0] header"
    next_header = text.index("\n## [", two_oh + 1)
    assert entry < next_header, "the entry drifted into an older release section"
