"""TRW's own launcher shim is not a shadow, and a hook settings.json registers must exist (2026-10-05).

* The 9.1.0 install warned twice that ``~/.local/bin/trw-mcp`` shadowed the install it had just made. That file is
  the bootstrap's launcher shim, ``exec "<venv>/bin/trw-mcp"``; the install's own path comes from RECORD as
  ``<venv>/lib/python3.x/site-packages/../../../bin/trw-mcp``, so a string match never recognized it.
* The same install deleted 17 registered hooks and still printed "ready". The installer's own doctor run now fails
  on them (``hook_family`` row; see ``test_install_hook_sweep_regression.py``).

Fake binaries in a temp dir only: no pip, no network, no real trw-mcp.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from tests._install_trw_pip_target_contract_support import _INSTALLER_PATHS, _load_installer_module

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(sys.platform == "win32", reason="the stubs are POSIX shell scripts"),
]

_BOTH = pytest.mark.parametrize("installer_path", _INSTALLER_PATHS, ids=["template", "artifact"])
_SHIM_HEADER = (
    "#!/usr/bin/env bash\n# TRW launcher shim → managed install. Regenerated by the installer; do not edit.\n"
)


def _executable(path: Path, body: str = "#!/bin/sh\nexit 0\n") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755)
    return path


def _machine(module, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, *, shim_to: Path | None = None) -> Path:
    """A managed venv whose RECORD-derived binary path has ``..`` segments, and a ~/.local/bin shim first on PATH."""
    venv = tmp_path / "share" / "trw" / "venv"
    installed = _executable(venv / "bin" / "trw-mcp")
    site = venv / "lib" / "python3.14" / "site-packages"
    site.mkdir(parents=True)
    monkeypatch.setattr(module, "_MCP_TARGET_BINARY", str(site / ".." / ".." / ".." / "bin" / "trw-mcp"))
    shim = _executable(tmp_path / "local-bin" / "trw-mcp", f'{_SHIM_HEADER}exec "{shim_to or installed}" "$@"\n')
    monkeypatch.setenv("PATH", f"{shim.parent}{os.pathsep}{os.environ.get('PATH', '')}")
    return shim


def _warnings(ui: MagicMock) -> str:
    return "\n".join(str(call.args[0]) for call in ui.step_warn.call_args_list)


def _restart(module, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, ui: MagicMock) -> None:
    monkeypatch.setattr(module, "_MCP_EFFECTIVE_VERSION", "9.1.0")
    monkeypatch.setattr(module, "_resolve_path_trw_mcp_version", lambda: "9.1.0")
    monkeypatch.setattr(module, "_write_version_yaml_metadata", lambda _target: None)
    (tmp_path / "project" / ".trw").mkdir(parents=True)
    module._restart_mcp_servers(tmp_path / "project", ui)


@_BOTH
def test_trws_own_launcher_shim_to_a_record_path_with_dotdot_segments_is_not_a_shadow(
    installer_path: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = _load_installer_module(installer_path)
    _machine(module, tmp_path, monkeypatch)
    ui = MagicMock()

    module._warn_if_another_trw_mcp_is_first_on_path(ui)
    _restart(module, tmp_path, monkeypatch, ui)

    assert _warnings(ui) == "", _warnings(ui)


@_BOTH
def test_a_launcher_shim_to_another_install_is_still_named_as_a_shadow(
    installer_path: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = _load_installer_module(installer_path)
    other = _executable(tmp_path / "other-venv" / "bin" / "trw-mcp")
    shim = _machine(module, tmp_path, monkeypatch, shim_to=other)
    ui = MagicMock()

    module._warn_if_another_trw_mcp_is_first_on_path(ui)
    _restart(module, tmp_path, monkeypatch, ui)

    warned = _warnings(ui)
    assert "first on your PATH" in warned, warned
    assert "is shadowing the intended" in warned, warned
    assert str(shim) in warned, warned


_SERVED_BOOTSTRAP = Path(__file__).resolve().parents[2] / "platform" / "public" / "install.sh"


def _distill_shim_script() -> str:
    """The served bootstrap's ``_expose_trw_bin`` and its post-installer trw-distill block, runnable on their own."""
    import re

    text = _SERVED_BOOTSTRAP.read_text(encoding="utf-8")
    expose = re.search(r"^_expose_trw_bin\(\) \{\n.*?^\}\n", text, re.MULTILINE | re.DOTALL)
    block = re.search(r"^_shim_dir=.*?^fi\n", text, re.MULTILINE | re.DOTALL)
    assert expose and block, "the served bootstrap lost the trw-distill launcher shim"
    return "set -euo pipefail\nwarn() { :; }\n_persist_bindir() { :; }\n" + expose.group(0) + block.group(0)


def _run_distill_block(home: Path) -> None:
    import subprocess

    env = {"HOME": str(home), "PATH": f"{home / '.local' / 'bin'}{os.pathsep}/usr/bin:/bin"}
    script = home / "distill-shim.sh"
    script.write_text(_distill_shim_script(), encoding="utf-8")
    subprocess.run(["bash", str(script)], env=env, check=True, capture_output=True, timeout=30)


@pytest.mark.skipif(not _SERVED_BOOTSTRAP.is_file(), reason="the served bootstrap is not in this checkout")
@pytest.mark.parametrize("prior", ["absent", "trw-shim", "users-own"])
def test_the_bootstrap_shims_trw_distill_beside_trws_own_trw_mcp_shim(tmp_path: Path, prior: str) -> None:
    venv_bin = tmp_path / "share" / "trw" / "venv" / "bin"
    distill = _executable(venv_bin / "trw-distill")
    _executable(venv_bin / "trw-mcp")
    local_bin = tmp_path / ".local" / "bin"
    _executable(local_bin / "trw-mcp", f'{_SHIM_HEADER}exec "{venv_bin}/trw-mcp" "$@"\n')
    users_own = "#!/bin/sh\necho mine\n"
    if prior == "trw-shim":
        _executable(local_bin / "trw-distill", f'{_SHIM_HEADER}exec "/old/venv/bin/trw-distill" "$@"\n')
    elif prior == "users-own":
        _executable(local_bin / "trw-distill", users_own)

    _run_distill_block(tmp_path)

    written = (local_bin / "trw-distill").read_text(encoding="utf-8")
    if prior == "users-own":
        assert written == users_own, "a trw-distill that is not TRW's shim is never replaced"
    else:
        assert f'exec "{distill}" "$@"' in written, written
        assert os.access(local_bin / "trw-distill", os.X_OK)


@pytest.mark.skipif(not _SERVED_BOOTSTRAP.is_file(), reason="the served bootstrap is not in this checkout")
def test_the_bootstrap_writes_no_trw_distill_shim_when_trw_mcp_is_not_trws_shim(tmp_path: Path) -> None:
    venv_bin = tmp_path / "pipx" / "venv" / "bin"
    _executable(venv_bin / "trw-distill")
    _executable(tmp_path / ".local" / "bin" / "trw-mcp", f'#!/bin/sh\nexec "{venv_bin}/trw-mcp" "$@"\n')

    _run_distill_block(tmp_path)

    assert not (tmp_path / ".local" / "bin" / "trw-distill").exists()
