"""REVIEW-MD-USER-EDIT-OVERWRITE (HB-2): a sync never overwrites a REVIEW.md the user edited.

``generate_review_md`` fully regenerated REVIEW.md on every sync/update, so a user's own review rules were
silently destroyed by the next sync. It now rewrites the file only when it is missing or still TRW-generated
(``is_generated_review_md``); an edited file is kept and reported (``kept_existing``, W2's shape), and
``force=True`` regenerates it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from trw_mcp.state.claude_md._sync import generate_review_md

pytestmark = [pytest.mark.usefixtures("no_memory_daemon"), pytest.mark.integration]


@pytest.fixture
def repo(tmp_path: Path) -> tuple[Path, Path]:
    trw_dir = tmp_path / ".trw"
    trw_dir.mkdir()
    return tmp_path, trw_dir


def test_a_missing_review_md_is_written(repo: tuple[Path, Path]) -> None:
    root, trw_dir = repo

    result = generate_review_md(trw_dir, repo_root=root)

    assert (root / "REVIEW.md").is_file()
    assert "kept_existing" not in result


def test_a_generated_review_md_is_regenerated(repo: tuple[Path, Path]) -> None:
    root, trw_dir = repo
    generate_review_md(trw_dir, repo_root=root)
    first = (root / "REVIEW.md").read_text(encoding="utf-8")

    result = generate_review_md(trw_dir, repo_root=root)

    # Not kept as a user edit (W2's REVIEW-MD-KEEP may still keep it for an empty store; that is its own guard).
    assert "edits TRW did not generate" not in str(result.get("kept_existing", ""))
    assert (root / "REVIEW.md").read_text(encoding="utf-8") == first


def test_a_user_edited_review_md_is_kept_and_reported(repo: tuple[Path, Path]) -> None:
    root, trw_dir = repo
    generate_review_md(trw_dir, repo_root=root)
    review = root / "REVIEW.md"
    edited = review.read_text(encoding="utf-8") + "\n## Our own rule\nNever merge on Fridays.\n"
    review.write_text(edited, encoding="utf-8")

    result = generate_review_md(trw_dir, repo_root=root)

    assert review.read_text(encoding="utf-8") == edited
    assert "edits TRW did not generate" in str(result.get("kept_existing", ""))
    assert "--force" in str(result.get("kept_existing", ""))


def test_force_regenerates_an_edited_review_md(repo: tuple[Path, Path]) -> None:
    root, trw_dir = repo
    generate_review_md(trw_dir, repo_root=root)
    review = root / "REVIEW.md"
    review.write_text("# hand-written\n", encoding="utf-8")

    # As `instructions sync --force` calls it (_profile_dispatcher sets both from --force).
    result = generate_review_md(trw_dir, repo_root=root, force=True, allow_empty=True)

    assert "kept_existing" not in result
    assert review.read_text(encoding="utf-8").startswith("# REVIEW.md — Auto-generated by TRW")


def test_with_learnings_to_inject_an_edited_review_md_is_still_kept(
    repo: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """The decisive case: the store HAS learnings, so REVIEW-MD-KEEP's empty-store guard does not apply."""
    root, trw_dir = repo
    monkeypatch.setattr(
        "trw_mcp.state.recall_factories.recall_for_review_tags",
        lambda *_a, **_k: [{"id": "L-abc1", "summary": "never swallow errors"}],
    )
    generate_review_md(trw_dir, repo_root=root)
    review = root / "REVIEW.md"
    assert "never swallow errors" in review.read_text(encoding="utf-8"), "precondition: learnings injected"
    edited = review.read_text(encoding="utf-8") + "\n## Our own rule\nNever merge on Fridays.\n"
    review.write_text(edited, encoding="utf-8")

    result = generate_review_md(trw_dir, repo_root=root)

    assert review.read_text(encoding="utf-8") == edited
    assert "edits TRW did not generate" in str(result.get("kept_existing", ""))


def test_a_user_flag_line_in_trws_own_format_is_kept(repo: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch) -> None:
    """Codex r1 P0: a rule the user writes in the generator's line format is still the user's edit."""
    root, trw_dir = repo
    monkeypatch.setattr(
        "trw_mcp.state.recall_factories.recall_for_review_tags",
        lambda *_a, **_k: [{"id": "L-abc1", "summary": "never swallow errors"}],
    )
    generate_review_md(trw_dir, repo_root=root)
    review = root / "REVIEW.md"
    line = "- Flag: never swallow errors (L-abc1)"
    edited = review.read_text(encoding="utf-8").replace(line, line + "\n- Flag: Never merge on Fridays (MY-RULE)")
    review.write_text(edited, encoding="utf-8")

    result = generate_review_md(trw_dir, repo_root=root)

    assert review.read_text(encoding="utf-8") == edited
    assert result["status"] == "skipped"


def test_update_project_keeps_a_committed_user_edit_and_says_so(tmp_path: Path) -> None:
    """E2E-INC-086 (swarm-e2e s15_review_edit): a COMMITTED user edit survived nothing -- update-project replaced
    REVIEW.md silently. It must keep the edit and name REVIEW.md in what it reports."""
    import subprocess

    from trw_mcp.bootstrap import init_project, update_project

    git = ["git", "-C", str(tmp_path), "-c", "user.name=t", "-c", "user.email=t@t", "-c", "commit.gpgsign=false"]
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    assert not init_project(tmp_path, ide="claude-code")["errors"]
    review = tmp_path / "REVIEW.md"
    edited = review.read_text(encoding="utf-8") + "\n## Our own rule\nNever merge on Fridays.\n"
    review.write_text(edited, encoding="utf-8")
    subprocess.run([*git, "add", "-A"], check=True)
    subprocess.run([*git, "commit", "-q", "--no-verify", "-m", "user edit"], check=True)

    result = update_project(tmp_path, ide="claude-code")

    assert review.read_text(encoding="utf-8") == edited
    reported = "\n".join(str(x) for key in ("warnings", "preserved", "info") for x in result.get(key, []))
    assert "REVIEW.md" in reported and "--force" in reported, reported


def test_a_kept_review_md_is_reported_even_when_the_sync_also_refused(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Codex r2 KI: a policy refusal returned early and dropped the REVIEW.md warning."""
    from trw_mcp.bootstrap._ide_targets_finalize import _run_claude_md_sync

    kept = "REVIEW.md kept: it has edits TRW did not generate (use --force to regenerate it)"
    monkeypatch.setattr(
        "trw_mcp.state.claude_md.execute_claude_md_sync",
        lambda **_k: {"refusals": [{"file": "AGENTS.md", "reason": "x"}], "review_md": {"kept_existing": kept}},
    )
    result: dict[str, list[str]] = {"updated": [], "created": [], "preserved": [], "errors": [], "warnings": []}

    _run_claude_md_sync(tmp_path, result)

    assert kept in result["warnings"]


@pytest.mark.parametrize("existed", [True, False])
def test_an_edit_saved_while_sync_is_building_the_file_is_kept(
    repo: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch, existed: bool
) -> None:
    """Codex r2 class (plan-then-act): ownership is re-proven on the bytes immediately before the rename."""
    root, trw_dir = repo
    review = root / "REVIEW.md"
    if existed:
        generate_review_md(trw_dir, repo_root=root)
    mine = "# My review rules\nSaved while TRW was recalling learnings.\n"

    def user_saves_during_recall(*_a: object, **_k: object) -> list[dict[str, str]]:
        review.write_text(mine, encoding="utf-8")
        return [{"id": "L-abc1", "summary": "never swallow errors"}]

    monkeypatch.setattr("trw_mcp.state.recall_factories.recall_for_review_tags", user_saves_during_recall)
    result = generate_review_md(trw_dir, repo_root=root)

    assert review.read_text(encoding="utf-8") == mine
    assert result["status"] == "skipped"
    assert not list(root.glob(".review-md-*.tmp")), "the unused temp file is removed"
