"""Split bootstrap multi-IDE init tests."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import tomllib

from trw_mcp.bootstrap import init_project


@pytest.mark.unit
class TestUpdateProjectMultiIDE:
    """FR15: Update-project supports multiple IDEs (PRD-CORE-074)."""

    def test_fr15_init_with_ide_opencode(self, tmp_path: Path) -> None:
        """init_project(ide='opencode') creates OpenCode config, instructions, and AGENTS.md."""
        (tmp_path / ".git").mkdir()

        result = init_project(tmp_path, ide="opencode")

        assert not result["errors"], result["errors"]
        # opencode.json created
        assert (tmp_path / "opencode.json").exists()
        config = json.loads((tmp_path / "opencode.json").read_text())
        assert "mcp" in config
        assert "trw" in config["mcp"]
        # Per-client instruction file created (PRD-CORE-115)
        assert (tmp_path / ".opencode" / "INSTRUCTIONS.md").exists()
        instructions = (tmp_path / ".opencode" / "INSTRUCTIONS.md").read_text()
        assert "trw_session_start" in instructions
        assert "trw_deliver" in instructions
        assert (tmp_path / "AGENTS.md").exists()
        assert (tmp_path / ".opencode" / "commands" / "trw-deliver.md").exists()
        assert (tmp_path / ".opencode" / "agents" / "trw-implementer.md").exists()
        assert (tmp_path / ".opencode" / "skills" / "trw-deliver" / "SKILL.md").exists()
        assert not (tmp_path / ".opencode" / "skills" / "trw-sprint-team").exists()

    def test_fr15_init_creates_both_ide_all(self, tmp_path: Path) -> None:
        """init_project(ide='all') creates Claude, OpenCode, and Codex artifacts."""
        (tmp_path / ".git").mkdir()

        result = init_project(tmp_path, ide="all")

        assert not result["errors"], result["errors"]
        # Claude Code artifacts
        assert (tmp_path / ".claude").is_dir()
        assert (tmp_path / "CLAUDE.md").exists()
        # OpenCode artifacts
        assert (tmp_path / "opencode.json").exists()
        # Codex artifacts
        assert (tmp_path / ".codex" / "config.toml").exists()
        assert not (tmp_path / ".codex" / "hooks.json").exists()
        assert (tmp_path / ".codex" / "agents" / "trw-implementer.toml").exists()
        assert (tmp_path / ".agents" / "skills" / "trw-deliver" / "SKILL.md").exists()
        # Per-client instruction files (PRD-CORE-115)
        assert (tmp_path / ".opencode" / "INSTRUCTIONS.md").exists()
        assert (tmp_path / ".codex" / "INSTRUCTIONS.md").exists()
        assert (tmp_path / "AGENTS.md").exists()

    def test_fr15_init_default_no_opencode_artifacts(self, tmp_path: Path) -> None:
        """init_project() without --ide does not create opencode artifacts by default."""
        (tmp_path / ".git").mkdir()
        # No opencode indicators — default auto-detect should fall back to claude-code

        result = init_project(tmp_path)

        assert not result["errors"], result["errors"]
        # opencode artifacts should NOT exist (no .opencode/ dir present)
        assert not (tmp_path / "opencode.json").exists()
        assert not (tmp_path / "AGENTS.md").exists()

    def test_fr15_opencode_instructions_contains_trw_section(self, tmp_path: Path) -> None:
        """Per-client instructions generated by init_project contain TRW tool reference."""
        (tmp_path / ".git").mkdir()

        result = init_project(tmp_path, ide="opencode")

        assert not result["errors"], result["errors"]
        instructions_content = (tmp_path / ".opencode" / "INSTRUCTIONS.md").read_text()
        # The per-client instructions should contain tool names
        assert "trw_session_start" in instructions_content or "TRW" in instructions_content

    def test_fr15_init_with_ide_codex(self, tmp_path: Path) -> None:
        """init_project(ide='codex') creates Codex config, AGENTS.md, and per-client instructions."""
        (tmp_path / ".git").mkdir()

        result = init_project(tmp_path, ide="codex")

        assert not result["errors"], result["errors"]
        config = tomllib.loads((tmp_path / ".codex" / "config.toml").read_text(encoding="utf-8"))
        assert config["features"]["hooks"] is False
        assert "codex_hooks" not in config["features"]
        assert config["mcp_servers"]["trw"]["enabled"] is True
        assert config["mcp_servers"]["openaiDeveloperDocs"]["enabled"] is True
        assert not (tmp_path / ".codex" / "hooks.json").exists()
        assert (tmp_path / ".codex" / "agents" / "trw-docs-researcher.toml").exists()
        assert (tmp_path / ".agents" / "skills" / "trw-deliver" / "SKILL.md").exists()
        # Per-client instruction file (PRD-CORE-115)
        assert (tmp_path / ".codex" / "INSTRUCTIONS.md").exists()
        instructions_content = (tmp_path / ".codex" / "INSTRUCTIONS.md").read_text(encoding="utf-8")
        assert "trw_deliver" in instructions_content
        assert (tmp_path / "AGENTS.md").exists()
