"""trw-mcp ``tier`` subcommand handlers (PRD-DIST-1996, cycle 748).

Closes the c746/c747 dev-key UX gap: operators no longer need to
hand-construct HMAC signatures. This module exposes ``tier issue`` +
``tier show`` to provision and inspect ``.trw/entitlements.yaml``.

v0 uses the hard-coded dev HMAC key from ``_entitlements.py``.
Production deployments override via ``TRW_ENTITLEMENT_KEY`` env var.
Real signing service deferred to v1.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

from trw_mcp.state._entitlements import (
    Entitlement,
    load_entitlement,
    sign_entitlement_for_dev,
)


def _normalize_expires_at(raw: str) -> str:
    """Parse a permissive expiry string to canonical ISO-8601 UTC.

    Accepts ``YYYY-MM-DD`` (interpreted as midnight UTC) or any
    ISO-8601 datetime. Returns canonical string used in signing.
    """
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        try:
            dt = datetime.strptime(raw, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        except ValueError as exc:
            raise SystemExit(
                f"tier issue: cannot parse --expires={raw!r}; use YYYY-MM-DD or ISO-8601 datetime"
            ) from exc
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.isoformat()


def _run_tier_issue(args: argparse.Namespace) -> None:
    """Generate a signed entitlement YAML."""
    expires_iso = _normalize_expires_at(args.expires)
    sig = sign_entitlement_for_dev(
        tier=args.tier,
        issued_to=args.issued_to,
        expires_at=expires_iso,
    )
    yaml_text = (
        f"# Generated by `trw-mcp tier issue` (PRD-DIST-1996, c748)\n"
        f"# v0 uses hard-coded dev HMAC key; production overrides via TRW_ENTITLEMENT_KEY\n"
        f"tier: {args.tier}\n"
        f"issued_to: {args.issued_to}\n"
        f"expires_at: '{expires_iso}'\n"
        f"signature: {sig}\n"
    )

    if args.print_only:
        sys.stdout.write(yaml_text)
        return

    trw_dir = Path(args.trw_dir)
    trw_dir.mkdir(parents=True, exist_ok=True)
    out_path = trw_dir / "entitlements.yaml"
    out_path.write_text(yaml_text, encoding="utf-8")
    print(f"tier issue: wrote {out_path}")
    print(f"  tier={args.tier}  issued_to={args.issued_to}  expires_at={expires_iso}")


def _run_tier_show(args: argparse.Namespace) -> None:
    """Resolve + print current entitlement status."""
    trw_dir = Path(getattr(args, "trw_dir", ".trw"))
    entitlement = load_entitlement(trw_dir)
    print(f"tier:      {entitlement.tier}")
    print(f"reason:    {entitlement.reason}")
    if entitlement.expires_at_iso:
        print(f"expires:   {entitlement.expires_at_iso}")
    if entitlement.signed_payload_keys:
        print(f"payload:   {','.join(entitlement.signed_payload_keys)}")
    features_enabled = [
        feature for feature in ("trw_before_edit_hint:distill_sidecar",) if entitlement.has_feature(feature)
    ]
    print(f"features:  {features_enabled or '(none)'}")


def _tier_status_rows(entitlement: Entitlement) -> list[tuple[str, str, str, str]]:
    """Build rows for the auditable tier status table."""
    limit_label = {
        "free": "baseline",
        "team": "team",
        "pro": "pro",
        "enterprise": "enterprise",
    }[entitlement.tier]
    expires = entitlement.expires_at_iso or "none"
    return [("active", entitlement.tier, limit_label, expires), ("reason", entitlement.reason, "-", "-")]


def _format_tier_status_table(entitlement: Entitlement) -> str:
    rows = _tier_status_rows(entitlement)
    lines = [
        "| state | entitlement | limit | expires |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(f"| {state} | {tier} | {limit} | {expires} |" for state, tier, limit, expires in rows)
    return "\n".join(lines)


def _run_tier_status(args: argparse.Namespace) -> None:
    """Print table-form tier status for operator audit trails."""
    entitlement = load_entitlement(Path(getattr(args, "trw_dir", ".trw")))
    print(_format_tier_status_table(entitlement))


def run_tier(args: argparse.Namespace) -> None:
    """Dispatch ``tier <subcommand>``."""
    subcommand = getattr(args, "tier_command", None)
    if subcommand == "issue":
        _run_tier_issue(args)
    elif subcommand == "show":
        _run_tier_show(args)
    elif subcommand == "status":
        _run_tier_status(args)
    else:
        print("Usage: trw-mcp tier {issue|show|status} [...]", file=sys.stderr)
        sys.exit(2)


__all__ = ["run_tier"]
