"""TRW Pydantic models — public re-exports for kept model sub-modules."""

# config
from trw_mcp.models.config import PhaseTimeCaps, TRWConfig

# learning
from trw_mcp.models.learning import (
    ContextArchitecture,
    ContextConventions,
    LearningEntry,
    LearningIndex,
    LearningStatus,
    Pattern,
    PatternIndex,
    Reflection,
    Script,
    ScriptIndex,
)

# report
from trw_mcp.models.report import (
    BuildSummary,
    DurationInfo,
    EventSummary,
    LearningSummary,
    PhaseEntry,
    RunReport,
)

# requirements
from trw_mcp.models.requirements import (
    ComplexityFactor,
    PRDConfidence,
    PRDDates,
    PRDEvidence,
    PRDFrontmatter,
    PRDMetrics,
    PRDQualityGates,
    PRDTraceability,
    Requirement,
    RiskLevel,
    TraceabilityResult,
    ValidationFailure,
    ValidationResult,
)

# run
from trw_mcp.models.run import (
    PHASE_ORDER,
    Event,
    EventType,
    OutputContract,
    Phase,
    ReversionTrigger,
    ReviewFinding,
    RunState,
    ShardCard,
    WaveEntry,
    WaveManifest,
)

# typed_dicts — canonical home for all TypedDicts (types.py re-exports from here)
from trw_mcp.models import typed_dicts
from trw_mcp.models.typed_dicts import (
    AutoProgressStepResult,
    CeremonyFeedbackEntry,
    CeremonyScoreResult,
    CheckpointEventDataDict,
    CheckpointRecordDict,
    CheckpointResultDict,
    DeliverResultDict,
    DeployFrameworksVersionDataDict,
    DimensionScoreDict,
    EmbedHealthStatus,
    EscalationResult,
    ImprovementSuggestionDict,
    LearnResult,
    LearnResultDict,
    LearningEntryCompactDict,
    LearningEntryDict,
    MypyResultDict,
    OutcomeCorrelationStepResult,
    ProgressionItem,
    PytestResultDict,
    RecallOutcomeStepResult,
    RecallResultDict,
    ReviewFindingDict,
    RunStatusDict,
    SectionScoreDict,
    SessionStartResultDict,
    TelemetryStepResult,
    TierDistribution,
    TierSweepStepResult,
    TrustIncrementResult,
    TrwInitConfigDataDict,
    ValidateResultDict,
    ValidationFailureDict,
)

__all__ = [
    "PHASE_ORDER",
    "BuildSummary",
    "ComplexityFactor",
    "ContextArchitecture",
    "ContextConventions",
    "DurationInfo",
    "Event",
    "EventSummary",
    "EventType",
    "LearningEntry",
    "LearningIndex",
    "LearningStatus",
    "LearningSummary",
    "OutputContract",
    "PRDConfidence",
    "PRDDates",
    "PRDEvidence",
    "PRDFrontmatter",
    "PRDMetrics",
    "PRDQualityGates",
    "PRDTraceability",
    "Pattern",
    "PatternIndex",
    "Phase",
    "PhaseEntry",
    "PhaseTimeCaps",
    "Reflection",
    "Requirement",
    "ReversionTrigger",
    "ReviewFinding",
    "RiskLevel",
    "RunReport",
    "RunState",
    "Script",
    "ScriptIndex",
    "ShardCard",
    "TRWConfig",
    "TraceabilityResult",
    "ValidationFailure",
    "ValidationResult",
    "WaveEntry",
    "WaveManifest",
    # TypedDicts (models.typed_dicts — canonical; models.types re-exports these)
    "typed_dicts",
    "AutoProgressStepResult",
    "CeremonyFeedbackEntry",
    "CeremonyScoreResult",
    "CheckpointResultDict",
    "DeliverResultDict",
    "DimensionScoreDict",
    "EmbedHealthStatus",
    "EscalationResult",
    "ImprovementSuggestionDict",
    "LearnResult",
    "LearnResultDict",
    "LearningEntryCompactDict",
    "LearningEntryDict",
    "MypyResultDict",
    "OutcomeCorrelationStepResult",
    "ProgressionItem",
    "PytestResultDict",
    "RecallOutcomeStepResult",
    "RecallResultDict",
    "ReviewFindingDict",
    "RunStatusDict",
    "SectionScoreDict",
    "SessionStartResultDict",
    "TelemetryStepResult",
    "TierDistribution",
    "TierSweepStepResult",
    "TrustIncrementResult",
    "TrwInitConfigDataDict",
    "ValidateResultDict",
    "ValidationFailureDict",
    "CheckpointEventDataDict",
    "CheckpointRecordDict",
    "DeployFrameworksVersionDataDict",
]
