"""Planning agent models — grooming plan, section analysis, agent roles.

PRD-CORE-011: Pydantic v2 models for the planning agent architecture.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ResearchScope(str, Enum):
    """Research depth for PRD grooming sessions."""

    FULL = "full"
    CODEBASE = "codebase"
    MINIMAL = "minimal"


class SectionStatus(str, Enum):
    """Status of a PRD section relative to grooming needs."""

    PLACEHOLDER = "placeholder"
    PARTIAL = "partial"
    COMPLETE = "complete"


class SectionAnalysis(BaseModel):
    """Analysis of a single PRD section for grooming planning.

    Attributes:
        section_name: Name of the AARE-F section (e.g. 'Problem Statement').
        section_number: 1-based section number.
        status: Whether the section is placeholder, partial, or complete.
        density: Content density ratio (substantive lines / total lines).
        substantive_lines: Count of lines with substantive content.
        total_lines: Total line count for the section.
        research_topics: Suggested research topics to fill the section.
    """

    model_config = ConfigDict(strict=True, use_enum_values=True)

    section_name: str
    section_number: int = Field(ge=1, le=12)
    status: SectionStatus
    density: float = Field(ge=0.0, le=1.0)
    substantive_lines: int = Field(ge=0)
    total_lines: int = Field(ge=0)
    research_topics: list[str] = Field(default_factory=list)


class GroomingPlan(BaseModel):
    """Structured grooming plan for a PRD.

    Generated by the pure-function analysis phase of trw_prd_groom.
    Contains everything needed to guide a prd-groomer agent session.

    Attributes:
        prd_id: PRD identifier (e.g. 'PRD-CORE-011').
        prd_path: Absolute path to the PRD file.
        current_completeness: Current completeness score (0.0-1.0).
        current_total_score: Current V2 total score (0-100).
        current_quality_tier: Current quality tier classification.
        target_completeness: Target completeness threshold for grooming.
        sections_needing_work: List of sections requiring grooming.
        sections_complete: List of sections that are already adequate.
        estimated_research_queries: Estimated number of research queries.
        estimated_iterations: Estimated validate-fix iterations needed.
        max_iterations: Maximum iterations allowed.
        research_scope: Research depth for this grooming session.
    """

    model_config = ConfigDict(strict=True, use_enum_values=True)

    prd_id: str
    prd_path: str
    current_completeness: float = Field(ge=0.0, le=1.0)
    current_total_score: float = Field(ge=0.0, le=100.0)
    current_quality_tier: str
    target_completeness: float = Field(ge=0.0, le=1.0, default=0.85)
    sections_needing_work: list[SectionAnalysis] = Field(default_factory=list)
    sections_complete: list[str] = Field(default_factory=list)
    estimated_research_queries: int = Field(ge=0)
    estimated_iterations: int = Field(ge=0)
    max_iterations: int = Field(ge=1, le=10, default=5)
    research_scope: ResearchScope = ResearchScope.FULL


class AgentRole(BaseModel):
    """Definition of a specialized planning agent role.

    Attributes:
        name: Agent identifier (e.g. 'prd-groomer').
        description: Short description of the agent's purpose.
        agent_file: Relative path to the agent definition file.
        model: LLM model to use (inherit, haiku, sonnet, opus).
        max_turns: Maximum agentic turns.
        allowed_tools: Tools the agent is permitted to use.
        disallowed_tools: Tools explicitly blocked.
        read_only: Whether the agent can modify files.
    """

    model_config = ConfigDict(strict=True)

    name: str
    description: str
    agent_file: str
    model: Literal["inherit", "haiku", "sonnet", "opus"] = "inherit"
    max_turns: int = Field(ge=1, default=100)
    allowed_tools: list[str] = Field(default_factory=list)
    disallowed_tools: list[str] = Field(default_factory=list)
    read_only: bool = False


# Pre-defined agent role registry (PRD-CORE-011 FR01-FR04)
PLANNING_AGENT_ROLES: dict[str, AgentRole] = {
    "prd-groomer": AgentRole(
        name="prd-groomer",
        description="PRD grooming specialist — researches, drafts, validates, iterates",
        agent_file=".claude/agents/prd-groomer.md",
        model="inherit",
        max_turns=100,
        allowed_tools=[
            "Read", "Grep", "Glob", "Bash", "Edit", "Write",
            "WebSearch", "WebFetch",
            "mcp__trw__trw_prd_validate",
            "mcp__trw__trw_recall",
            "mcp__trw__trw_event",
            "mcp__trw__trw_shard_context",
        ],
        disallowed_tools=["NotebookEdit"],
    ),
    "requirement-writer": AgentRole(
        name="requirement-writer",
        description="EARS-compliant requirement drafting specialist",
        agent_file=".claude/agents/requirement-writer.md",
        model="inherit",
        max_turns=50,
        allowed_tools=[
            "Read", "Grep", "Glob", "Bash", "Write", "Edit", "WebSearch",
            "mcp__trw__trw_recall",
            "mcp__trw__trw_event",
        ],
        disallowed_tools=["NotebookEdit"],
    ),
    "requirement-reviewer": AgentRole(
        name="requirement-reviewer",
        description="Read-only PRD quality review agent",
        agent_file=".claude/agents/requirement-reviewer.md",
        model="inherit",
        max_turns=30,
        allowed_tools=[
            "Read", "Grep", "Glob", "Bash", "WebSearch",
            "mcp__trw__trw_prd_validate",
            "mcp__trw__trw_recall",
        ],
        disallowed_tools=["Write", "Edit", "NotebookEdit"],
        read_only=True,
    ),
    "traceability-checker": AgentRole(
        name="traceability-checker",
        description="Bidirectional traceability verification agent (Haiku model)",
        agent_file=".claude/agents/traceability-checker.md",
        model="haiku",
        max_turns=30,
        allowed_tools=[
            "Read", "Grep", "Glob", "Bash",
            "mcp__trw__trw_traceability_check",
            "mcp__trw__trw_recall",
        ],
        disallowed_tools=["Write", "Edit", "NotebookEdit", "WebSearch", "WebFetch"],
        read_only=True,
    ),
}
