"""Re-exports from typed_dicts for backward compatibility.

.. deprecated::
    All source-code imports from this module have been migrated to
    ``trw_mcp.models.typed_dicts`` (the canonical location).  This shim is
    retained **only** to avoid breaking external consumers.  Do NOT add new
    imports here — import directly from ``trw_mcp.models.typed_dicts`` instead.

All TypedDicts originally defined here have been consolidated into
``trw_mcp.models.typed_dicts``.  This module re-exports them so existing
``from trw_mcp.models.types import ...`` call-sites continue to work without
modification.
"""

from trw_mcp.models.typed_dicts import (
    AggregateMetrics,
    AnalyticsReport,
    AuditCeremonyComplianceResult,
    AuditDuplicatePairDict,
    AuditDuplicatesResult,
    AuditFixActionsDict,
    AuditHookVersionsResult,
    AuditIndexConsistencyResult,
    AuditLearningsResult,
    AuditRecallEffectivenessResult,
    AuditReflectionComponentsDict,
    AuditReflectionDiagnosticsDict,
    AuditReflectionQualityResult,
    AuditReport,
    AuditTelemetryBloatDict,
    AutoProgressStepResult,
    AutoReviewResult,
    BatchSendResult,
    CeremonyFeedbackEntry,
    CeremonyFeedbackStepResult,
    CeremonyScoreResult,
    CeremonyTrendItem,
    CheckpointEventDataDict,
    CheckpointRecordDict,
    DedupHandleResult,
    EscalationResult,
    ExportAnalyticsSection,
    ExportMetadata,
    ExportRunsSection,
    ExportSummary,
    IndexSyncResult,
    MultiReviewerAnalysisResult,
    ProgressionItem,
    PublishLearningsResult,
    PublishResult,
    ReconcileReviewResult,
    ReviewTrendResult,
    RoadmapSyncResult,
    RunAnalysisResult,
    SessionRecallExtrasDict,
    StatusReflectionDict,
    StatusReversionLatestDict,
    StatusReversionMetricsDict,
    SyncIndexMdResult,
    TelemetryStepResult,
    TierMetrics,
    TrustIncrementResult,
    TrwStatusDict,
)

__all__ = [
    "AggregateMetrics",
    "AnalyticsReport",
    "AuditCeremonyComplianceResult",
    "AuditDuplicatePairDict",
    "AuditDuplicatesResult",
    "AuditFixActionsDict",
    "AuditHookVersionsResult",
    "AuditIndexConsistencyResult",
    "AuditLearningsResult",
    "AuditRecallEffectivenessResult",
    "AuditReflectionComponentsDict",
    "AuditReflectionDiagnosticsDict",
    "AuditReflectionQualityResult",
    "AuditReport",
    "AuditTelemetryBloatDict",
    "AutoProgressStepResult",
    "AutoReviewResult",
    "BatchSendResult",
    "CeremonyFeedbackEntry",
    "CeremonyFeedbackStepResult",
    "CeremonyScoreResult",
    "CeremonyTrendItem",
    "CheckpointEventDataDict",
    "CheckpointRecordDict",
    "DedupHandleResult",
    "EscalationResult",
    "ExportAnalyticsSection",
    "ExportMetadata",
    "ExportRunsSection",
    "ExportSummary",
    "IndexSyncResult",
    "MultiReviewerAnalysisResult",
    "ProgressionItem",
    "PublishLearningsResult",
    "PublishResult",
    "ReconcileReviewResult",
    "ReviewTrendResult",
    "RoadmapSyncResult",
    "RunAnalysisResult",
    "SessionRecallExtrasDict",
    "StatusReflectionDict",
    "StatusReversionLatestDict",
    "StatusReversionMetricsDict",
    "SyncIndexMdResult",
    "TelemetryStepResult",
    "TierMetrics",
    "TrustIncrementResult",
    "TrwStatusDict",
]
