"""Pure f-string template renderers for Copilot distill channels.

No Jinja2, no unsubstituted vars. All templates return complete rendered strings.
Used by C1 (_instructions_distill.py), C2 (_path_instructions.py), and C3 (_vscode_mcp.py).

PRD-DIST-2406.
"""

from __future__ import annotations

__all__ = [
    "render_c1_t0_beacon",
    "render_c1_t1_segment",
    "render_c2_path_instructions",
    "render_c3_mcp_json",
]


def render_c1_t0_beacon(*, ts: str) -> str:
    """Render the T0 presence beacon for C1.

    The beacon is permanent and non-prunable (FR04, P1-14).
    Token count: <= 35.

    Args:
        ts: ISO-8601 UTC timestamp string.

    Returns:
        Beacon string without surrounding markers.
    """
    return (
        f"<!-- trw-distill sha=none ts={ts} "
        "regenerate: trw-distill self-improve risk-report --repo . --persist-sidecar -->\n"
        "Run: trw-distill self-improve risk-report --repo . --persist-sidecar"
    )


def render_c1_t1_segment(
    *,
    conventions: list[str],
    hotspots: list[str],
    max_conventions: int = 3,
    max_hotspots: int = 3,
) -> str:
    """Render the T1 content segment for C1 (copilot-instructions.md).

    Budget: top-3 conventions + top-3 hotspot warnings.
    Does NOT include markers or provenance — those are added by the renderer.

    Args:
        conventions: List of convention strings from sidecar.
        hotspots: List of hotspot strings from sidecar.
        max_conventions: Maximum number of conventions to include.
        max_hotspots: Maximum number of hotspots to include.

    Returns:
        Rendered T1 content string.
    """
    top_convs = conventions[:max_conventions]
    top_spots = hotspots[:max_hotspots]

    lines: list[str] = []
    lines.append("## TRW Distill")

    if top_convs:
        lines.append("**Conventions:**")
        for c in top_convs:
            text = c if isinstance(c, str) else str(c)
            lines.append(f"- {text}")

    if top_spots:
        lines.append("**Hotspot warnings:**")
        for h in top_spots:
            text = h if isinstance(h, str) else str(h)
            lines.append(f"- {text}")

    return "\n".join(lines)


def render_c2_path_instructions(
    *,
    apply_to: str,
    hotspot_entries: list[dict[str, object]],
    ts: str,
) -> str:
    """Render the full .instructions.md content for C2.

    Args:
        apply_to: Minimatch directory glob string (e.g. 'backend/routers/**/*.py').
        hotspot_entries: List of hotspot dicts with 'file', 'risk_score', 'reason' keys.
        ts: ISO-8601 UTC timestamp string.

    Returns:
        Full file content including YAML frontmatter.
    """
    lines: list[str] = [
        "---",
        f'applyTo: "{apply_to}"',
        "---",
        "",
        "# TRW Distill — Hotspot Warnings",
        "",
        f"<!-- generated by trw-mcp at {ts} -->",
        "<!-- regenerate: trw-distill self-improve risk-report --repo . --persist-sidecar -->",
        "",
    ]

    if hotspot_entries:
        lines.append("## High-Risk Files")
        lines.append("")
        for entry in hotspot_entries:
            path = entry.get("file", entry.get("path", "unknown"))
            score = entry.get("risk_score", entry.get("score", 0.0))
            reason = entry.get("reason", entry.get("summary", ""))
            score_str = f"{float(score):.2f}" if isinstance(score, (int, float)) else "N/A"
            reason_part = f" — {reason}" if reason else ""
            lines.append(f"- `{path}` (risk: {score_str}){reason_part}")
        lines.append("")

    lines.append("_Path-scoped instructions active in VS Code Copilot and cloud agent only._")
    lines.append("_NOT active in bare CLI sessions._")

    return "\n".join(lines) + "\n"


def render_c3_mcp_json(*, existing: dict[str, object], trw_entry: dict[str, object]) -> dict[str, object]:
    """Merge the TRW MCP server entry into an existing mcp.json dict.

    Modifies the 'servers' top-level key. Preserves all other keys.

    Args:
        existing: Existing mcp.json content as a dict (may be empty).
        trw_entry: The TRW server entry to merge under servers.trw.

    Returns:
        New merged dict (does not mutate existing).
    """
    result = dict(existing)
    existing_servers = result.get("servers", {})
    servers: dict[str, object] = dict(existing_servers) if isinstance(existing_servers, dict) else {}
    servers["trw"] = trw_entry
    result["servers"] = servers
    return result
