#!/usr/bin/env bash
# install-trw.sh — Self-contained TRW Framework installer
# Generated by: python scripts/build_installer.py
# Version: {{VERSION}}
#
# Usage:
#   bash install-trw.sh                 # Interactive install in current directory
#   bash install-trw.sh /path/to        # Install in specified directory
#   bash install-trw.sh --upgrade       # Upgrade package only (skip init-project)
#   bash install-trw.sh --ai            # Install with AI/LLM extras
#   bash install-trw.sh --script --ai   # Non-interactive with AI extras
#   bash install-trw.sh --name myproj --api-key trw_abc123  # Headless with config
#   curl ... | bash                     # Headless mode (auto-detected)
#
# Re-run with a newer version of this script to upgrade.

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────
WHEEL_FILENAME="{{WHEEL_FILENAME}}"
MEMORY_WHEEL_FILENAME="{{MEMORY_WHEEL_FILENAME}}"
TRW_VERSION="{{VERSION}}"
MIN_PYTHON_VERSION="3.10"

# ── Mode flags (set during argument parsing) ──────────────────────────
INTERACTIVE=false
QUIET=false
INSTALL_AI=""          # "" = unset (prompt), "yes", "no"
INSTALL_SQLITEVEC=""   # "" = unset (prompt), "yes", "no"
OPT_PROJECT_NAME=""    # --name flag value
OPT_API_KEY=""         # --api-key flag value
OPT_TELEMETRY=""       # "" = unset, "yes", "no"
PLATFORM_STATUS=""     # Set after config: "connected", "telemetry", "offline"

# ── Color output ──────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ── Output helpers ────────────────────────────────────────────────────
info() {
    if [ "$QUIET" = false ]; then
        echo -e "${GREEN}[TRW]${NC} $*"
    fi
}

warn() {
    echo -e "${YELLOW}[TRW]${NC} $*"
}

error() {
    echo -e "${RED}[TRW]${NC} $*" >&2
}

# Interactive-mode output helpers
step_header() {
    local step="$1"
    local total="$2"
    local label="$3"
    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo -e "  ${BOLD}Step ${step}/${total}${NC}  ${label}"
    else
        info "${label}"
    fi
}

step_ok() {
    local msg="$1"
    if [ "$INTERACTIVE" = true ]; then
        echo -e "            ${GREEN}✓${NC} ${msg}"
    elif [ "$QUIET" = false ]; then
        info "$msg"
    fi
}

step_warn() {
    local msg="$1"
    if [ "$INTERACTIVE" = true ]; then
        echo -e "            ${YELLOW}!${NC} ${msg}"
    else
        warn "$msg"
    fi
}

step_fail() {
    local msg="$1"
    if [ "$INTERACTIVE" = true ]; then
        echo -e "            ${RED}✗${NC} ${msg}"
    else
        error "$msg"
    fi
}

# ── Spinner ───────────────────────────────────────────────────────────
# Usage: start_spinner "message"; long_command; stop_spinner $? "ok" "fail"
SPINNER_PID=""
SPINNER_MSG_FILE=""

start_spinner() {
    if [ "$INTERACTIVE" = false ]; then
        return
    fi
    local msg="$1"
    SPINNER_MSG_FILE=$(mktemp)
    echo "$msg" > "$SPINNER_MSG_FILE"
    (
        local frames='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
        local i=0
        while true; do
            local frame="${frames:$i:1}"
            local current_msg
            current_msg=$(cat "$SPINNER_MSG_FILE" 2>/dev/null || echo "$msg")
            printf "\r\033[K            %s %s" "$frame" "$current_msg"
            i=$(( (i + 1) % ${#frames} ))
            sleep 0.1
        done
    ) &
    SPINNER_PID=$!
    # Ensure spinner is killed on script exit
    trap 'kill $SPINNER_PID 2>/dev/null; rm -rf "$tmpdir" 2>/dev/null; rm -f "$SPINNER_MSG_FILE" 2>/dev/null' EXIT
}

# Update the spinner's displayed message without stopping it
update_spinner() {
    if [ -n "$SPINNER_MSG_FILE" ] && [ -f "$SPINNER_MSG_FILE" ]; then
        echo "$1" > "$SPINNER_MSG_FILE"
    fi
}

stop_spinner() {
    if [ "$INTERACTIVE" = false ]; then
        return
    fi
    local exit_code="$1"
    local ok_msg="$2"
    local fail_msg="${3:-Failed}"
    if [ -n "$SPINNER_PID" ]; then
        kill "$SPINNER_PID" 2>/dev/null || true
        wait "$SPINNER_PID" 2>/dev/null || true
        SPINNER_PID=""
        printf "\r\033[K"  # Clear spinner line
    fi
    if [ -n "$SPINNER_MSG_FILE" ]; then
        rm -f "$SPINNER_MSG_FILE" 2>/dev/null
        SPINNER_MSG_FILE=""
    fi
    if [ "$exit_code" -eq 0 ]; then
        step_ok "$ok_msg"
    else
        step_fail "$fail_msg"
    fi
    # Restore normal trap
    trap 'rm -rf "$tmpdir" 2>/dev/null' EXIT
}

# ── Run command with live progress ────────────────────────────────────
# Streams command output and updates spinner message with each line.
# In script mode, shows prefixed output directly.
# Usage: run_with_progress "fallback msg" command args...
run_with_progress() {
    local fallback_msg="$1"
    shift
    local log_file
    log_file=$(mktemp)
    local file_count=0

    if [ "$INTERACTIVE" = true ]; then
        start_spinner "$fallback_msg"
        # Run command, parse output in real time, update spinner
        "$@" > "$log_file" 2>&1 &
        local cmd_pid=$!
        local last_size=0
        while kill -0 "$cmd_pid" 2>/dev/null; do
            local current_size
            current_size=$(wc -c < "$log_file" 2>/dev/null || echo 0)
            if [ "$current_size" -gt "$last_size" ]; then
                last_size=$current_size
                # Parse latest lines for progress
                local last_line
                last_line=$(tail -1 "$log_file" 2>/dev/null | sed 's/^  //' | head -c 60)
                if echo "$last_line" | grep -qE '(Updated|Created|Preserved|synced|WARNING):?'; then
                    file_count=$((file_count + 1))
                    local short
                    short=$(echo "$last_line" | sed 's/Updated: //;s/Created (new): //;s/Preserved: //')
                    update_spinner "${fallback_msg} (${file_count} files) ${DIM}${short}${NC}"
                fi
            fi
            sleep 0.3
        done
        wait "$cmd_pid" 2>/dev/null
        local rc=$?
        rm -f "$log_file"
        return $rc
    else
        # Script mode: run normally, show output with prefix
        "$@" 2>&1 | while IFS= read -r line; do
            if [ "$QUIET" = false ]; then
                echo -e "${GREEN}[TRW]${NC}   $line"
            fi
        done
        local rc=${PIPESTATUS[0]}
        rm -f "$log_file"
        return $rc
    fi
}

# ── Python version check ─────────────────────────────────────────────
find_python() {
    local py=""
    for candidate in python3 python; do
        if command -v "$candidate" &>/dev/null; then
            py="$candidate"
            break
        fi
    done

    if [ -z "$py" ]; then
        error "Python not found. Install Python >= ${MIN_PYTHON_VERSION}"
        exit 1
    fi

    local major minor
    major=$("$py" -c "import sys; print(sys.version_info.major)")
    minor=$("$py" -c "import sys; print(sys.version_info.minor)")

    if [ "$major" -lt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -lt 10 ]; }; then
        error "Python ${major}.${minor} found but >= ${MIN_PYTHON_VERSION} required"
        exit 1
    fi

    PYTHON_VERSION="${major}.${minor}"
    PYTHON_PATH="$(command -v "$py")"
    echo "$py"
}

# ── pip install with fallback ─────────────────────────────────────────
# Tries normal, --user, --break-system-packages in order
pip_install() {
    local python_cmd="$1"
    local pkg="$2"
    local label="$3"
    local pip_quiet="--quiet"

    if "$python_cmd" -m pip install --upgrade "$pkg" $pip_quiet 2>/dev/null; then
        return 0
    elif "$python_cmd" -m pip install --upgrade --user "$pkg" $pip_quiet 2>/dev/null; then
        step_warn "Installed ${label} with --user (PEP 668 managed environment)"
        return 0
    elif "$python_cmd" -m pip install --upgrade --break-system-packages "$pkg" $pip_quiet 2>/dev/null; then
        step_warn "Installed ${label} with --break-system-packages (consider using a venv)"
        return 0
    else
        return 1
    fi
}

# ── Extract embedded wheels ───────────────────────────────────────────
extract_memory_wheel() {
    local python_cmd="$1"
    local dest="$2"

    # Extract base64 data between __MEMORY_WHEEL_DATA__ and __WHEEL_DATA__ markers
    sed -n '/^__MEMORY_WHEEL_DATA__$/,/^__WHEEL_DATA__$/ p' "$0" \
        | tail -n +2 \
        | head -n -1 \
        | "$python_cmd" -c "
import sys, base64
data = sys.stdin.read().strip()
sys.stdout.buffer.write(base64.b64decode(data))
" > "$dest"
}

extract_wheel() {
    local python_cmd="$1"
    local dest="$2"

    # Use Python for cross-platform base64 decode (works on macOS + Linux)
    sed -n '/^__WHEEL_DATA__$/,$ p' "$0" \
        | tail -n +2 \
        | "$python_cmd" -c "
import sys, base64
data = sys.stdin.read().strip()
sys.stdout.buffer.write(base64.b64decode(data))
" > "$dest"
}

# ── Interactive prompts ───────────────────────────────────────────────
prompt_yes_no() {
    local question="$1"
    local default="${2:-n}"  # "y" or "n"
    local hint
    if [ "$default" = "y" ]; then
        hint="[Y/n]"
    else
        hint="[y/N]"
    fi

    local answer
    printf "    %s %s " "$question" "$hint"
    read -r answer </dev/tty
    answer="${answer:-$default}"
    case "$answer" in
        [Yy]*) return 0 ;;
        *) return 1 ;;
    esac
}

# ── Input sanitization ────────────────────────────────────────────────
sanitize_project_name() {
    local input="$1"
    # Lowercase
    local result
    result=$(echo "$input" | tr '[:upper:]' '[:lower:]')
    # Replace non-alphanumeric with hyphens
    result=$(echo "$result" | sed 's/[^a-z0-9]/-/g')
    # Collapse multiple hyphens
    result=$(echo "$result" | sed 's/-\{2,\}/-/g')
    # Strip leading/trailing hyphens
    result=$(echo "$result" | sed 's/^-//;s/-$//')
    # Truncate to 64 chars
    result=$(echo "$result" | cut -c1-64)
    # Strip trailing hyphen again (from truncation)
    result=$(echo "$result" | sed 's/-$//')
    echo "$result"
}

validate_api_key() {
    local key="$1"
    # Must start with trw_, only alphanumeric and underscores, max 128 chars
    if [ ${#key} -gt 128 ]; then
        return 1
    fi
    if echo "$key" | grep -qE '^trw_[a-zA-Z0-9_]+$'; then
        return 0
    fi
    return 1
}

prompt_input() {
    local prompt_text="$1"
    local default_val="${2:-}"
    local result
    if [ -n "$default_val" ]; then
        printf "    %s [%s] " "$prompt_text" "$default_val"
    else
        printf "    %s " "$prompt_text"
    fi
    read -r result </dev/tty
    result="${result:-$default_val}"
    echo "$result"
}

# ── Banner ────────────────────────────────────────────────────────────
show_banner() {
    if [ "$QUIET" = true ]; then
        return
    fi
    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo -e "${CYAN}╭──────────────────────────────────────────╮${NC}"
        echo -e "${CYAN}│${NC}  ${BOLD}TRW Framework Installer v${TRW_VERSION}${NC}$(printf '%*s' $((10 - ${#TRW_VERSION})) '')${CYAN}│${NC}"
        echo -e "${CYAN}│${NC}  ${DIM}Engineering memory for Claude Code${NC}      ${CYAN}│${NC}"
        echo -e "${CYAN}╰──────────────────────────────────────────╯${NC}"
    else
        echo -e "${BOLD}TRW Framework Installer v${TRW_VERSION}${NC}"
        echo ""
    fi
}

show_success_banner() {
    if [ "$QUIET" = true ]; then
        info "TRW Framework v${TRW_VERSION} installed."
        return
    fi
    local platform_line=""
    case "$PLATFORM_STATUS" in
        connected) platform_line="Connected to trwframework.com" ;;
        telemetry) platform_line="Anonymous telemetry enabled" ;;
        *)         platform_line="Offline mode (run installer again to connect)" ;;
    esac

    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo -e "${GREEN}╭──────────────────────────────────────────╮${NC}"
        echo -e "${GREEN}│${NC}  ${GREEN}${BOLD}✓ TRW Framework v${TRW_VERSION} — ready${NC}$(printf '%*s' $((13 - ${#TRW_VERSION})) '')${GREEN}│${NC}"
        echo -e "${GREEN}╰──────────────────────────────────────────╯${NC}"
        echo ""
        echo -e "  ${DIM}${platform_line}${NC}"
        echo ""
        echo -e "  Next steps:"
        echo -e "    1. Start Claude Code:  ${BOLD}claude${NC}"
        echo -e "    2. TRW tools are automatically available"
        echo ""
        echo -e "  ${DIM}Re-run this script anytime to upgrade.${NC}"
    else
        echo ""
        echo -e "${GREEN}${BOLD}TRW Framework v${TRW_VERSION} — ready${NC}"
        echo ""
        info "${platform_line}"
        info "Next steps:"
        info "  1. Start Claude Code:  claude"
        info "  2. TRW tools are automatically available"
        echo ""
        info "Re-run this script anytime to upgrade."
    fi
}

# ── Main ──────────────────────────────────────────────────────────────
main() {
    local upgrade_only=false
    local target_dir="."
    local force_script=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --upgrade)
                upgrade_only=true
                shift
                ;;
            --ai)
                INSTALL_AI="yes"
                shift
                ;;
            --no-ai)
                INSTALL_AI="no"
                shift
                ;;
            --sqlite-vec)
                INSTALL_SQLITEVEC="yes"
                shift
                ;;
            --no-sqlite-vec)
                INSTALL_SQLITEVEC="no"
                shift
                ;;
            --quiet|-q)
                QUIET=true
                shift
                ;;
            --script)
                force_script=true
                shift
                ;;
            --name)
                OPT_PROJECT_NAME="$2"
                shift 2
                ;;
            --api-key)
                OPT_API_KEY="$2"
                shift 2
                ;;
            --telemetry)
                OPT_TELEMETRY="yes"
                shift
                ;;
            --no-telemetry)
                OPT_TELEMETRY="no"
                shift
                ;;
            --help|-h)
                echo "Usage: bash install-trw.sh [OPTIONS] [TARGET_DIR]"
                echo ""
                echo "Install TRW Framework in a project directory."
                echo ""
                echo "Arguments:"
                echo "  TARGET_DIR          Project directory (default: current directory)"
                echo ""
                echo "Options:"
                echo "  --upgrade           Upgrade package only, skip project setup"
                echo "  --ai                Install AI/LLM extras (embeddings, analysis)"
                echo "  --no-ai             Skip AI extras (default in script mode)"
                echo "  --sqlite-vec        Install sqlite-vec for vector search"
                echo "  --no-sqlite-vec     Skip sqlite-vec (default in script mode)"
                echo "  --name NAME         Set project name (installation ID)"
                echo "  --api-key KEY       Set platform API key"
                echo "  --telemetry         Enable anonymous usage telemetry"
                echo "  --no-telemetry      Disable telemetry"
                echo "  --quiet, -q         Minimal output"
                echo "  --script            Force non-interactive mode (no prompts)"
                echo "  --help, -h          Show this help message"
                echo ""
                echo "Interactive mode (default when run in a terminal):"
                echo "  Prompts for optional features, shows progress spinners."
                echo ""
                echo "Script/headless mode (piped input or --script):"
                echo "  No prompts, quiet output. Use --ai/--sqlite-vec flags."
                echo ""
                echo "Examples:"
                echo "  bash install-trw.sh                    # Interactive install"
                echo "  bash install-trw.sh --script --ai      # Headless with AI extras"
                echo "  curl ... | bash                        # Piped (headless, no extras)"
                exit 0
                ;;
            -*)
                error "Unknown option: $1 (use --help for usage)"
                exit 1
                ;;
            *)
                target_dir="$1"
                shift
                ;;
        esac
    done

    # Detect interactive mode: terminal on stdin, not forced to script mode
    if [ "$force_script" = false ] && [ -t 0 ]; then
        INTERACTIVE=true
    fi

    # In script mode, default unset flags to "no" (no prompts)
    if [ "$INTERACTIVE" = false ]; then
        INSTALL_AI="${INSTALL_AI:-no}"
        INSTALL_SQLITEVEC="${INSTALL_SQLITEVEC:-no}"
    fi

    target_dir="$(cd "$target_dir" 2>/dev/null && pwd)" || {
        error "Directory not found: $target_dir"
        exit 1
    }

    # Pre-calculate total steps from known flags (recalculated after prompts)
    local total_steps=4  # python, extract, install-base, project-setup
    if [ "$INSTALL_AI" = "yes" ]; then total_steps=$((total_steps + 1)); fi
    if [ "$INSTALL_SQLITEVEC" = "yes" ]; then total_steps=$((total_steps + 1)); fi

    show_banner

    # ── Step 1: Find Python ───────────────────────────────────────────
    step_header 1 "$total_steps" "Checking Python environment"

    local python_cmd
    PYTHON_VERSION=""
    PYTHON_PATH=""
    python_cmd=$(find_python 2>/dev/null)

    if [ -z "$python_cmd" ]; then
        step_fail "Python not found (>= ${MIN_PYTHON_VERSION} required)"
        exit 1
    fi

    # Re-extract version for display (find_python sets PYTHON_VERSION)
    if [ -z "$PYTHON_VERSION" ]; then
        PYTHON_VERSION=$("$python_cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        PYTHON_PATH="$(command -v "$python_cmd")"
    fi
    step_ok "Python ${PYTHON_VERSION} (${PYTHON_PATH})"

    # ── Step 2: Extract embedded wheels ───────────────────────────────
    step_header 2 "$total_steps" "Extracting embedded packages"

    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' EXIT

    local memory_wheel_path="${tmpdir}/${MEMORY_WHEEL_FILENAME}"
    start_spinner "Extracting trw-memory..."
    extract_memory_wheel "$python_cmd" "$memory_wheel_path"
    local extract_rc=$?
    stop_spinner $extract_rc "Extracted trw-memory wheel"

    if [ ! -s "$memory_wheel_path" ]; then
        step_fail "Failed to extract trw-memory wheel data"
        exit 1
    fi

    local wheel_path="${tmpdir}/${WHEEL_FILENAME}"
    start_spinner "Extracting trw-mcp..."
    extract_wheel "$python_cmd" "$wheel_path"
    extract_rc=$?
    stop_spinner $extract_rc "Extracted trw-mcp wheel"

    if [ ! -s "$wheel_path" ]; then
        step_fail "Failed to extract trw-mcp wheel data"
        exit 1
    fi

    # ── Optional features prompt (interactive only) ───────────────────
    if [ "$INTERACTIVE" = true ] && { [ -z "$INSTALL_AI" ] || [ -z "$INSTALL_SQLITEVEC" ]; }; then
        echo ""
        echo -e "  ${BOLD}Optional features:${NC}"

        if [ -z "$INSTALL_AI" ]; then
            if prompt_yes_no "Install AI/LLM features? (embeddings, analysis)"; then
                INSTALL_AI="yes"
            else
                INSTALL_AI="no"
            fi
        fi

        if [ -z "$INSTALL_SQLITEVEC" ]; then
            if prompt_yes_no "Install sqlite-vec for vector search?"; then
                INSTALL_SQLITEVEC="yes"
            else
                INSTALL_SQLITEVEC="no"
            fi
        fi
    fi

    # Recalculate total steps based on selections
    total_steps=4  # python, extract, install-base, project-setup
    local extra_steps=0
    if [ "$INSTALL_AI" = "yes" ]; then
        extra_steps=$((extra_steps + 1))
    fi
    if [ "$INSTALL_SQLITEVEC" = "yes" ]; then
        extra_steps=$((extra_steps + 1))
    fi
    # Add configuration step: always in interactive mode, only if flags provided in script mode
    local has_config_step=false
    if [ "$INTERACTIVE" = true ]; then
        has_config_step=true
    elif [ -n "$OPT_PROJECT_NAME" ] || [ -n "$OPT_API_KEY" ]; then
        has_config_step=true
    fi
    if [ "$has_config_step" = true ]; then
        extra_steps=$((extra_steps + 1))
    fi
    total_steps=$((total_steps + extra_steps))
    local current_step=3

    # ── Step 3: Install base packages ─────────────────────────────────
    step_header "$current_step" "$total_steps" "Installing base packages"

    # Install trw-memory
    start_spinner "Installing trw-memory..."
    pip_install "$python_cmd" "$memory_wheel_path" "trw-memory"
    local pip_rc=$?
    stop_spinner $pip_rc "Installed trw-memory" "pip install failed for trw-memory"

    if [ $pip_rc -ne 0 ]; then
        error "pip install failed for trw-memory — try installing in a virtual environment:"
        error "  python3 -m venv .venv && source .venv/bin/activate"
        error "  bash install-trw.sh"
        exit 1
    fi

    # Install trw-mcp
    start_spinner "Installing trw-mcp v${TRW_VERSION}..."
    pip_install "$python_cmd" "$wheel_path" "trw-mcp"
    pip_rc=$?
    stop_spinner $pip_rc "Installed trw-mcp v${TRW_VERSION}" "pip install failed for trw-mcp"

    if [ $pip_rc -ne 0 ]; then
        error "pip install failed for trw-mcp — try installing in a virtual environment:"
        error "  python3 -m venv .venv && source .venv/bin/activate"
        error "  bash install-trw.sh"
        exit 1
    fi

    # Verify both packages
    if ! "$python_cmd" -c "import trw_memory" 2>/dev/null; then
        step_fail "trw_memory module not importable after install"
        exit 1
    fi
    if ! "$python_cmd" -c "import trw_mcp" 2>/dev/null; then
        step_fail "trw_mcp module not importable after install"
        exit 1
    fi

    current_step=$((current_step + 1))

    # ── Step N: Install AI extras (if requested) ──────────────────────
    if [ "$INSTALL_AI" = "yes" ]; then
        step_header "$current_step" "$total_steps" "Installing AI extras"

        start_spinner "Installing trw-mcp[ai]..."
        pip_install "$python_cmd" "trw-mcp[ai]" "trw-mcp[ai]"
        pip_rc=$?
        stop_spinner $pip_rc "AI features enabled" "Failed to install AI extras (non-fatal)"

        if [ $pip_rc -ne 0 ]; then
            step_warn "AI extras failed to install — base TRW still works"
        fi

        current_step=$((current_step + 1))
    fi

    # ── Step N: Install sqlite-vec (if requested) ─────────────────────
    if [ "$INSTALL_SQLITEVEC" = "yes" ]; then
        step_header "$current_step" "$total_steps" "Installing sqlite-vec"

        start_spinner "Installing sqlite-vec..."
        pip_install "$python_cmd" "sqlite-vec" "sqlite-vec"
        pip_rc=$?
        stop_spinner $pip_rc "sqlite-vec enabled" "Failed to install sqlite-vec (non-fatal)"

        if [ $pip_rc -ne 0 ]; then
            step_warn "sqlite-vec failed to install — TRW works without it"
        fi

        current_step=$((current_step + 1))
    fi

    # ── Step N: Project setup ─────────────────────────────────────────
    step_header "$current_step" "$total_steps" "Setting up project"

    if [ "$upgrade_only" = true ]; then
        step_ok "Upgrade complete (--upgrade flag: skipping project setup)"
    elif [ ! -d "${target_dir}/.git" ]; then
        step_warn "Not a git repository — skipping project setup"
        step_warn "After initializing git, run: trw-mcp init-project ."
    elif [ -d "${target_dir}/.trw" ]; then
        # Existing installation -> update
        local setup_cmd
        if command -v trw-mcp &>/dev/null; then
            setup_cmd="trw-mcp"
        else
            setup_cmd="$python_cmd -m trw_mcp.server"
        fi
        run_with_progress "Updating project..." $setup_cmd update-project "${target_dir}"
        local setup_rc=$?
        stop_spinner $setup_rc "Project updated" "Project update failed"
    else
        # Fresh install
        local setup_cmd
        if command -v trw-mcp &>/dev/null; then
            setup_cmd="trw-mcp"
        else
            setup_cmd="$python_cmd -m trw_mcp.server"
        fi
        run_with_progress "Initializing project..." $setup_cmd init-project "${target_dir}"
        local setup_rc=$?
        stop_spinner $setup_rc "Project initialized" "Project setup failed"
    fi

    current_step=$((current_step + 1))

    # ── Step N: Configure project ──────────────────────────────────────
    if [ "$has_config_step" = true ]; then
        step_header "$current_step" "$total_steps" "Configure your project"

        local project_name=""
        local api_key=""
        local telemetry_enabled="false"
        local default_name
        default_name=$(basename "$target_dir")
        default_name=$(sanitize_project_name "$default_name")

        if [ "$INTERACTIVE" = true ]; then
            # ── a) Project name ──
            local raw_name
            raw_name=$(prompt_input "Project name (identifies this installation):" "$default_name")
            project_name=$(sanitize_project_name "$raw_name")

            # Validate: must match pattern (or be empty -> use default)
            if [ -z "$project_name" ]; then
                project_name="$default_name"
            fi

            if ! echo "$project_name" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
                step_warn "Could not sanitize name, using default"
                project_name="$default_name"
            fi

            if [ "$project_name" != "$raw_name" ] && [ -n "$raw_name" ]; then
                step_ok "Project name: ${project_name} (sanitized from '${raw_name}')"
            else
                step_ok "Project name: ${project_name}"
            fi

            # ── b) Platform API key ──
            local key_attempts=0
            local max_key_attempts=3  # initial + 2 retries
            while [ $key_attempts -lt $max_key_attempts ]; do
                local raw_key
                raw_key=$(prompt_input "Platform API key (optional, press Enter to skip):")
                # Strip whitespace
                raw_key=$(echo "$raw_key" | tr -d '[:space:]')

                if [ -z "$raw_key" ]; then
                    step_ok "No API key — skipping platform connection"
                    break
                fi

                if validate_api_key "$raw_key"; then
                    api_key="$raw_key"
                    telemetry_enabled="true"
                    step_ok "API key accepted"
                    break
                else
                    key_attempts=$((key_attempts + 1))
                    if [ $key_attempts -lt $max_key_attempts ]; then
                        step_warn "Invalid format (must start with trw_ and contain only alphanumeric/underscores). Try again:"
                    else
                        step_warn "Invalid format — skipping API key"
                    fi
                fi
            done

            # ── c) Telemetry opt-in (only if no API key) ──
            if [ -z "$api_key" ]; then
                if prompt_yes_no "Enable anonymous usage telemetry? (helps improve TRW)"; then
                    telemetry_enabled="true"
                    step_ok "Telemetry enabled"
                else
                    step_ok "Telemetry disabled"
                fi
            fi
        else
            # Script mode: use flags
            if [ -n "$OPT_PROJECT_NAME" ]; then
                project_name=$(sanitize_project_name "$OPT_PROJECT_NAME")
            else
                project_name="$default_name"
            fi

            if [ -n "$OPT_API_KEY" ]; then
                if validate_api_key "$OPT_API_KEY"; then
                    api_key="$OPT_API_KEY"
                    telemetry_enabled="true"
                else
                    warn "Invalid API key format — ignoring --api-key"
                fi
            fi

            if [ -z "$api_key" ] && [ "$OPT_TELEMETRY" = "yes" ]; then
                telemetry_enabled="true"
            fi
            if [ "$OPT_TELEMETRY" = "no" ]; then
                telemetry_enabled="false"
            fi

            step_ok "Project name: ${project_name}"
        fi

        # ── Write configuration to .trw/config.yaml ──
        local config_path="${target_dir}/.trw/config.yaml"
        if [ -f "$config_path" ]; then
            "$python_cmd" - "$config_path" "$project_name" "$api_key" "$telemetry_enabled" << 'PYEOF'
import sys

config_path = sys.argv[1]
project_name = sys.argv[2]
api_key = sys.argv[3]
telemetry_enabled = sys.argv[4] == "true"

# Read existing config
with open(config_path) as f:
    lines = f.readlines()

# Track which keys we've already updated
updated_keys = set()
new_lines = []
platform_url = "https://api.trwframework.com"

for line in lines:
    stripped = line.lstrip()
    # Update installation_id
    if stripped.startswith("installation_id:"):
        new_lines.append(f"installation_id: {project_name}\n")
        updated_keys.add("installation_id")
        continue
    # Update platform_api_key
    if stripped.startswith("platform_api_key:"):
        if api_key:
            new_lines.append(f'platform_api_key: "{api_key}"\n')
        else:
            new_lines.append(line)
        updated_keys.add("platform_api_key")
        continue
    # Update platform_telemetry_enabled
    if stripped.startswith("platform_telemetry_enabled:"):
        new_lines.append(f"platform_telemetry_enabled: {'true' if telemetry_enabled else 'false'}\n")
        updated_keys.add("platform_telemetry_enabled")
        continue
    # Remove existing platform_urls block (we'll re-add if needed)
    if stripped.startswith("platform_urls:"):
        updated_keys.add("platform_urls")
        continue
    # Skip list items belonging to platform_urls
    if stripped.startswith("- ") and "platform_urls" in updated_keys and "platform_urls_done" not in updated_keys:
        continue
    # Any non-list-item line ends the platform_urls block
    if "platform_urls" in updated_keys and "platform_urls_done" not in updated_keys and not stripped.startswith("- "):
        updated_keys.add("platform_urls_done")
    # Skip commented-out platform config hints (from default config template)
    if stripped.startswith("# platform_urls:") or stripped.startswith('#   - "https://api.') or stripped.startswith("# platform_api_key:") or stripped.startswith("# platform_telemetry_enabled:") or stripped.startswith("# Platform telemetry"):
        continue
    new_lines.append(line)

# Append missing keys
if "installation_id" not in updated_keys:
    new_lines.append(f"installation_id: {project_name}\n")
if api_key and "platform_api_key" not in updated_keys:
    new_lines.append(f'platform_api_key: "{api_key}"\n')
if telemetry_enabled and "platform_telemetry_enabled" not in updated_keys:
    new_lines.append(f"platform_telemetry_enabled: true\n")
if (api_key or telemetry_enabled):
    new_lines.append(f"platform_urls:\n")
    new_lines.append(f'  - "{platform_url}"\n')

with open(config_path, "w") as f:
    f.writelines(new_lines)
PYEOF
            local config_rc=$?
            if [ $config_rc -eq 0 ]; then
                step_ok "Configuration saved to .trw/config.yaml"
            else
                step_warn "Failed to update config — you can set these manually"
            fi
        else
            step_warn "Config file not found — run project setup first"
        fi

        # Set platform status for success banner
        if [ -n "$api_key" ]; then
            PLATFORM_STATUS="connected"
        elif [ "$telemetry_enabled" = "true" ]; then
            PLATFORM_STATUS="telemetry"
        else
            PLATFORM_STATUS="offline"
        fi

        current_step=$((current_step + 1))
    else
        PLATFORM_STATUS="offline"
    fi

    # ── Success ───────────────────────────────────────────────────────
    show_success_banner
}

main "$@"
exit 0

# ── Embedded wheel data (do not edit below this line) ─────────────────
__MEMORY_WHEEL_DATA__
{{MEMORY_WHEEL_BASE64}}
__WHEEL_DATA__
{{WHEEL_BASE64}}
