#!/usr/bin/env python3
"""install-trw.py — Self-contained TRW Framework installer.

Generated by: python scripts/build_installer.py
Version: {{VERSION}}

Usage:
    python3 install-trw.py                    # Interactive install
    python3 install-trw.py /path/to           # Install in specified directory
    python3 install-trw.py --upgrade          # Upgrade existing installation
    python3 install-trw.py --script --ai      # Non-interactive with AI extras
    python3 install-trw.py --name myproj      # Set project name
    curl ... | python3 -                      # Headless mode (auto-detected)

Re-run with a newer version of this script to upgrade.
"""

from __future__ import annotations

import argparse
import base64
import re
import shutil
import subprocess
import sys
import tempfile
import threading
from pathlib import Path

# ── Configuration (substituted by build_installer.py) ────────────────
TRW_VERSION = "{{VERSION}}"
WHEEL_FILENAME = "{{WHEEL_FILENAME}}"
MEMORY_WHEEL_FILENAME = "{{MEMORY_WHEEL_FILENAME}}"
MIN_PYTHON_VERSION = (3, 10)
DOCS_BASE = "https://trwframework.com/docs"

# ── ANSI colors ──────────────────────────────────────────────────────
_USE_COLOR = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()

RED = "\033[0;31m" if _USE_COLOR else ""
GREEN = "\033[0;32m" if _USE_COLOR else ""
YELLOW = "\033[0;33m" if _USE_COLOR else ""
BLUE = "\033[0;34m" if _USE_COLOR else ""
CYAN = "\033[0;36m" if _USE_COLOR else ""
BOLD = "\033[1m" if _USE_COLOR else ""
DIM = "\033[2m" if _USE_COLOR else ""
NC = "\033[0m" if _USE_COLOR else ""

_ANSI_RE = re.compile(r"\033\[[0-9;]*m")


def _visible_len(text: str) -> int:
    """Return the display width of *text* (strip ANSI escapes)."""
    return len(_ANSI_RE.sub("", text))


# ── Box drawing ──────────────────────────────────────────────────────

def draw_box(
    lines: list[str],
    color: str = CYAN,
    width: int = 52,
    padding: int = 2,
) -> None:
    """Draw a Unicode box with proper alignment.

    *width* is the total box width including border characters.
    *padding* is left margin inside the box.
    """
    inner = width - 2
    hbar = "\u2500" * inner
    tl, tr, bl, br, vb = "\u256d", "\u256e", "\u2570", "\u256f", "\u2502"
    print(f"{color}{tl}{hbar}{tr}{NC}")
    for line in lines:
        vis = _visible_len(line)
        gap = " " * max(0, inner - padding - vis)
        margin = " " * padding
        print(f"{color}{vb}{NC}{margin}{line}{gap}{color}{vb}{NC}")
    print(f"{color}{bl}{hbar}{br}{NC}")


def draw_divider(label: str = "", color: str = DIM) -> None:
    """Print a subtle divider with optional centered label."""
    if label:
        print(f"\n  {color}\u2500\u2500 {label} \u2500\u2500{NC}")
    else:
        print()


# ── Output helpers ───────────────────────────────────────────────────

class UI:
    """Output helper that adapts to interactive/quiet/script modes."""

    def __init__(self, interactive: bool = False, quiet: bool = False) -> None:
        self.interactive = interactive
        self.quiet = quiet
        self._spinner: _Spinner | None = None

    def info(self, msg: str) -> None:
        if not self.quiet:
            print(f"{GREEN}[TRW]{NC} {msg}")

    def warn(self, msg: str) -> None:
        print(f"{YELLOW}[TRW]{NC} {msg}")

    def error(self, msg: str) -> None:
        print(f"{RED}[TRW]{NC} {msg}", file=sys.stderr)

    def blank(self) -> None:
        if not self.quiet:
            print()

    def step_header(self, step: int, total: int, label: str) -> None:
        if self.interactive:
            print(f"\n  {BOLD}Step {step}/{total}{NC}  {label}")
        else:
            self.info(label)

    def step_ok(self, msg: str) -> None:
        if self.interactive:
            print(f"            {GREEN}\u2713{NC} {msg}")
        elif not self.quiet:
            self.info(msg)

    def step_warn(self, msg: str) -> None:
        if self.interactive:
            print(f"            {YELLOW}!{NC} {msg}")
        else:
            self.warn(msg)

    def step_fail(self, msg: str) -> None:
        if self.interactive:
            print(f"            {RED}\u2717{NC} {msg}")
        else:
            self.error(msg)

    def hint(self, msg: str) -> None:
        """Show a dim hint line (interactive only)."""
        if self.interactive:
            print(f"    {DIM}{msg}{NC}")

    def doc_link(self, anchor: str) -> None:
        """Show a docs link hint."""
        self.hint(f"Learn more: {DOCS_BASE}/{anchor}")

    # ── Spinner ──────────────────────────────────────────────────────

    def start_spinner(self, msg: str) -> None:
        if not self.interactive:
            return
        self._spinner = _Spinner(msg)
        self._spinner.start()

    def update_spinner(self, msg: str) -> None:
        if self._spinner is not None:
            self._spinner.message = msg

    def stop_spinner(self, success: bool, ok_msg: str, fail_msg: str = "Failed") -> None:
        if self._spinner is not None:
            self._spinner.stop()
            self._spinner = None
            sys.stdout.write("\r\033[K")
            sys.stdout.flush()
        if success:
            self.step_ok(ok_msg)
        else:
            self.step_fail(fail_msg)


class _Spinner:
    """Braille-character spinner in a daemon thread."""

    _FRAMES = "\u280b\u2819\u2839\u2838\u283c\u2834\u2826\u2827\u2807\u280f"

    def __init__(self, message: str) -> None:
        self.message = message
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=2.0)

    def _run(self) -> None:
        idx = 0
        while not self._stop.is_set():
            frame = self._FRAMES[idx % len(self._FRAMES)]
            sys.stdout.write(f"\r\033[K            {frame} {self.message}")
            sys.stdout.flush()
            idx += 1
            self._stop.wait(0.1)


# ── Input helpers ────────────────────────────────────────────────────

def _open_tty():  # noqa: ANN202 — returns TextIO | None
    """Open /dev/tty for reading, or None if unavailable."""
    try:
        return open("/dev/tty", "r")  # noqa: SIM115
    except OSError:
        return None


def prompt_yes_no(question: str, default: str = "n") -> bool:
    """Prompt for yes/no. Returns True for yes."""
    hint = "[Y/n]" if default == "y" else "[y/N]"
    tty = _open_tty()
    if tty is None:
        return default == "y"
    try:
        sys.stdout.write(f"    {question} {hint} ")
        sys.stdout.flush()
        answer = tty.readline().strip() or default
    finally:
        tty.close()
    return answer.lower().startswith("y")


def prompt_input(prompt_text: str, default: str = "") -> str:
    """Prompt for text input."""
    display = f"    {prompt_text}"
    if default:
        display += f" [{default}]"
    display += " "
    tty = _open_tty()
    if tty is None:
        return default
    try:
        sys.stdout.write(display)
        sys.stdout.flush()
        answer = tty.readline().strip() or default
    finally:
        tty.close()
    return answer


def prompt_choice(label: str, options: list[str], default: int = 0) -> int:
    """Prompt user to select from numbered options. Returns index."""
    print(f"    {label}")
    for i, opt in enumerate(options):
        marker = f"{BOLD}>{NC}" if i == default else " "
        print(f"    {marker} {i + 1}. {opt}")
    tty = _open_tty()
    if tty is None:
        return default
    try:
        sys.stdout.write(f"    Choice [{default + 1}]: ")
        sys.stdout.flush()
        raw = tty.readline().strip()
    finally:
        tty.close()
    if not raw:
        return default
    try:
        choice = int(raw) - 1
        if 0 <= choice < len(options):
            return choice
    except ValueError:
        pass
    return default


# ── Prior installation detection ─────────────────────────────────────

def _load_prior_config(target_dir: Path) -> dict[str, object]:
    """Load prior installation config from .trw/config.yaml if it exists.

    Returns a dict with keys that were previously configured, or empty dict
    for first-time installs. Parses YAML manually — no pyyaml dependency.
    """
    config_path = target_dir / ".trw" / "config.yaml"
    if not config_path.is_file():
        return {}

    prior: dict[str, object] = {}
    try:
        for line in config_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("#") or not line or ":" not in line:
                continue
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key == "installation_id":
                prior["project_name"] = value
            elif key == "platform_api_key":
                prior["api_key"] = value
            elif key == "platform_telemetry_enabled":
                prior["telemetry"] = value.lower() == "true"
            elif key == "embeddings_enabled":
                prior["embeddings"] = value.lower() == "true"
    except OSError:
        pass
    return prior


def _detect_installed_extras(python: str) -> dict[str, bool]:
    """Detect which optional extras are already installed."""
    extras: dict[str, bool] = {}
    extras["ai"] = _run_quiet([python, "-c", "import anthropic"])
    extras["sqlite_vec"] = _run_quiet([python, "-c", "import sqlite_vec"])
    return extras


# ── Validation / sanitization ────────────────────────────────────────

def sanitize_project_name(name: str) -> str:
    """Lowercase, strip non-alphanumeric, collapse hyphens, truncate to 64."""
    result = name.lower()
    result = re.sub(r"[^a-z0-9]", "-", result)
    result = re.sub(r"-{2,}", "-", result)
    return result.strip("-")[:64].rstrip("-")


def validate_api_key(key: str) -> bool:
    """Check *key* matches trw_ prefix, alphanumeric+underscore, max 128."""
    return len(key) <= 128 and bool(re.match(r"^trw_[a-zA-Z0-9_]+$", key))


# ── Python discovery ─────────────────────────────────────────────────

def check_python_version(ui: UI) -> str:
    """Verify Python meets minimum version. Returns executable path."""
    major, minor = sys.version_info[:2]
    if (major, minor) < MIN_PYTHON_VERSION:
        ui.error(
            f"Python {major}.{minor} found but "
            f">= {MIN_PYTHON_VERSION[0]}.{MIN_PYTHON_VERSION[1]} required"
        )
        sys.exit(1)
    return sys.executable


# ── Wheel extraction ─────────────────────────────────────────────────

def _extract_wheel_data(marker: str) -> bytes:
    """Read base64 data following *marker* from this script file.

    Wheels are embedded as comment lines after marker comments at the
    end of the file (e.g. MEMORY_WHEEL_DATA, WHEEL_DATA). Each marker
    is followed by comment-prefixed base64 lines.
    """
    script_path = (
        Path(sys.argv[0]).resolve()
        if sys.argv[0] != "-"
        else Path(__file__).resolve()
    )
    text = script_path.read_text(encoding="utf-8", errors="replace")

    collecting = False
    b64_chunks: list[str] = []

    for line in text.splitlines():
        stripped = line.strip()
        if stripped == f"# {marker}":
            collecting = True
            continue
        if collecting:
            if stripped.startswith("# __") and stripped.endswith("__"):
                break
            if stripped.startswith("# "):
                b64_chunks.append(stripped[2:])
            elif stripped == "#":
                continue
            else:
                break

    if not b64_chunks:
        raise RuntimeError(f"No embedded data found for marker {marker}")

    return base64.b64decode("".join(b64_chunks))


def extract_wheels(tmpdir: Path) -> tuple[Path, Path]:
    """Extract both embedded wheels into *tmpdir*.

    Returns (memory_wheel_path, mcp_wheel_path).
    """
    memory_path = tmpdir / MEMORY_WHEEL_FILENAME
    memory_path.write_bytes(_extract_wheel_data("__MEMORY_WHEEL_DATA__"))

    mcp_path = tmpdir / WHEEL_FILENAME
    mcp_path.write_bytes(_extract_wheel_data("__WHEEL_DATA__"))

    return memory_path, mcp_path


# ── pip install with fallback ────────────────────────────────────────

def _run_quiet(cmd: list[str]) -> bool:
    """Run a command silently, return True if exit code == 0."""
    try:
        return subprocess.run(
            cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        ).returncode == 0
    except FileNotFoundError:
        return False


def pip_install(python: str, package: str, label: str, ui: UI) -> bool:
    """Try pip install with escalating fallbacks.

    Tries: normal -> --user -> --break-system-packages.
    """
    base = [python, "-m", "pip", "install", "--upgrade", "--quiet"]

    if _run_quiet(base + [package]):
        return True

    if _run_quiet(base + ["--user", package]):
        ui.step_warn(f"Installed {label} with --user (PEP 668 managed environment)")
        return True

    if _run_quiet(base + ["--break-system-packages", package]):
        ui.step_warn(f"Installed {label} with --break-system-packages")
        return True

    return False


# ── Run command with live progress ───────────────────────────────────

def run_with_progress(ui: UI, fallback_msg: str, cmd: list[str]) -> bool:
    """Run *cmd* showing live progress. Returns True on success."""
    try:
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
        )
    except FileNotFoundError:
        return False

    assert proc.stdout is not None

    if ui.interactive:
        ui.start_spinner(fallback_msg)
        file_count = 0
        for line in proc.stdout:
            line = line.strip()
            if re.search(r"(Updated|Created|Preserved|synced|WARNING):?", line):
                file_count += 1
                short = re.sub(r"^(Updated: |Created \(new\): |Preserved: )", "", line)[:60]
                ui.update_spinner(f"{fallback_msg} ({file_count} files) {DIM}{short}{NC}")
    else:
        for line in proc.stdout:
            if not ui.quiet:
                print(f"{GREEN}[TRW]{NC}   {line.rstrip()}")

    proc.wait()
    return proc.returncode == 0


# ── Config file update ───────────────────────────────────────────────

def update_config(
    config_path: Path,
    project_name: str,
    api_key: str,
    telemetry_enabled: bool,
) -> bool:
    """Update .trw/config.yaml with installation settings."""
    if not config_path.is_file():
        return False

    lines = config_path.read_text(encoding="utf-8").splitlines(keepends=True)
    platform_url = "https://api.trwframework.com"

    updated: set[str] = set()
    out: list[str] = []

    for line in lines:
        s = line.lstrip()

        if s.startswith("installation_id:"):
            out.append(f"installation_id: {project_name}\n")
            updated.add("installation_id")
            continue
        if s.startswith("platform_api_key:"):
            out.append(f'platform_api_key: "{api_key}"\n' if api_key else line)
            updated.add("platform_api_key")
            continue
        if s.startswith("platform_telemetry_enabled:"):
            val = "true" if telemetry_enabled else "false"
            out.append(f"platform_telemetry_enabled: {val}\n")
            updated.add("platform_telemetry_enabled")
            continue
        if s.startswith("platform_urls:"):
            updated.add("platform_urls")
            continue
        if s.startswith("- ") and "platform_urls" in updated and "platform_urls_done" not in updated:
            continue
        if "platform_urls" in updated and "platform_urls_done" not in updated and not s.startswith("- "):
            updated.add("platform_urls_done")

        # Skip commented-out platform config hints
        skip_prefixes = (
            "# platform_urls:", '#   - "https://api.',
            "# platform_api_key:", "# platform_telemetry_enabled:",
            "# Platform telemetry",
        )
        if any(s.startswith(p) for p in skip_prefixes):
            continue

        out.append(line)

    # Append missing keys
    if "installation_id" not in updated:
        out.append(f"installation_id: {project_name}\n")
    if api_key and "platform_api_key" not in updated:
        out.append(f'platform_api_key: "{api_key}"\n')
    if telemetry_enabled and "platform_telemetry_enabled" not in updated:
        out.append("platform_telemetry_enabled: true\n")
    if api_key or telemetry_enabled:
        out.append("platform_urls:\n")
        out.append(f'  - "{platform_url}"\n')

    config_path.write_text("".join(out), encoding="utf-8")
    return True


# ── Banners ──────────────────────────────────────────────────────────

def show_banner(ui: UI) -> None:
    """Display the installer header banner."""
    if ui.quiet:
        return
    if ui.interactive:
        print()
        draw_box(
            [
                f"{BOLD}TRW Framework Installer{NC}  v{TRW_VERSION}",
                "",
                f"{DIM}The Real Work \u2014 Accumulated Intelligence{NC}",
            ],
            color=CYAN,
        )
    else:
        print(f"{BOLD}TRW Framework Installer v{TRW_VERSION}{NC}")
        print()


def show_success_banner(ui: UI, platform_status: str, features: list[str]) -> None:
    """Display the post-install success banner with summary."""
    if ui.quiet:
        ui.info(f"TRW Framework v{TRW_VERSION} installed.")
        return

    status_map = {
        "connected": f"{GREEN}\u2022{NC} Connected to trwframework.com",
        "telemetry": f"{BLUE}\u2022{NC} Anonymous telemetry enabled",
    }
    status_line = status_map.get(
        platform_status,
        f"{DIM}\u2022 Offline mode (re-run installer to connect){NC}",
    )

    if ui.interactive:
        print()
        draw_box(
            [f"{GREEN}{BOLD}\u2713 TRW Framework v{TRW_VERSION} \u2014 ready{NC}"],
            color=GREEN,
        )
        print()

        # Summary
        print(f"  {status_line}")
        if features:
            feat_str = ", ".join(features)
            print(f"  {DIM}Extras: {feat_str}{NC}")
        print()

        # Next steps
        print(f"  {BOLD}Get started:{NC}")
        print(f"    {CYAN}1.{NC} Open your project in Claude Code:  {BOLD}claude{NC}")
        print(f"    {CYAN}2.{NC} TRW tools load automatically \u2014 just start working")
        print(f"    {CYAN}3.{NC} Call {BOLD}trw_session_start(){NC} for context from prior sessions")
        print()
        print(f"  {DIM}Upgrade anytime: python3 install-trw.py --upgrade{NC}")
        print(f"  {DIM}Full docs: {DOCS_BASE}/integration{NC}")
    else:
        print()
        print(f"{GREEN}{BOLD}TRW Framework v{TRW_VERSION} \u2014 ready{NC}")
        print()
        ui.info("Next: open your project in Claude Code — TRW tools load automatically.")
        ui.info(f"Docs: {DOCS_BASE}/integration")


# ── IDE detection and selection ──────────────────────────────────────

def _detect_installed_clis() -> list[str]:
    """Detect which AI coding CLI binaries are on PATH."""
    detected = []
    if shutil.which("claude"):
        detected.append("claude-code")
    if shutil.which("opencode"):
        detected.append("opencode")
    return detected


def _detect_project_ides(project_dir: str) -> list[str]:
    """Detect which IDE configs exist in the project."""
    import os as _os
    detected = []
    if _os.path.isdir(_os.path.join(project_dir, ".claude")):
        detected.append("claude-code")
    if _os.path.isdir(_os.path.join(project_dir, ".opencode")) or _os.path.isfile(
        _os.path.join(project_dir, "opencode.json")
    ):
        detected.append("opencode")
    return detected


def _prompt_ide_selection(detected_clis: list[str], detected_ides: list[str]) -> str | None:
    """Prompt user to select which IDE(s) to configure.

    Returns: "claude-code", "opencode", "all", or None (skip).
    """
    # Show what was detected
    if detected_clis:
        print(f"{GREEN}[TRW]{NC} Detected CLI(s): {', '.join(detected_clis)}")
    if detected_ides:
        print(f"{GREEN}[TRW]{NC} Existing IDE config: {', '.join(detected_ides)}")

    # Build options list: key, label, value
    options: list[tuple[str, str, str | None]] = []
    has_claude = "claude-code" in detected_clis or "claude-code" in detected_ides
    has_opencode = "opencode" in detected_clis or "opencode" in detected_ides

    if has_claude:
        options.append(("1", "Claude Code only", "claude-code"))
    if has_opencode:
        key = "2" if has_claude else "1"
        options.append((key, "OpenCode only", "opencode"))

    # Always offer "both" and "skip"
    both_key = str(len(options) + 1)
    options.append((both_key, "Both Claude Code and OpenCode", "all"))
    skip_key = "s"
    options.append((skip_key, "Skip (configure later)", None))

    print("\nConfigure TRW for:")
    for key, label, _ in options:
        print(f"  [{key}] {label}")

    default_key = options[0][0]
    tty = _open_tty()
    if tty is None:
        return options[0][2]
    try:
        sys.stdout.write(f"\nSelection [default: {default_key}]: ")
        sys.stdout.flush()
        choice = tty.readline().strip().lower() or default_key
    finally:
        tty.close()

    for key, _, value in options:
        if choice == key:
            return value
    return options[0][2]  # default to first option


# ── Find trw-mcp command ─────────────────────────────────────────────

def find_trw_cmd(python: str) -> list[str]:
    """Return the command list for invoking trw-mcp CLI."""
    if shutil.which("trw-mcp"):
        return ["trw-mcp"]
    return [python, "-m", "trw_mcp.server"]


# ── Installation phases ──────────────────────────────────────────────

def phase_check_python(ui: UI, step: int, total: int) -> str:
    """Phase 1: Verify Python version. Returns executable path."""
    ui.step_header(step, total, "Checking Python environment")
    python = check_python_version(ui)
    major, minor = sys.version_info[:2]
    ui.step_ok(f"Python {major}.{minor} ({python})")
    return python


def phase_extract_wheels(ui: UI, step: int, total: int, tmpdir: Path) -> tuple[Path, Path]:
    """Phase 2: Extract embedded wheel files."""
    ui.step_header(step, total, "Extracting embedded packages")
    ui.start_spinner("Extracting wheels...")
    try:
        memory_whl, mcp_whl = extract_wheels(tmpdir)
        ok = memory_whl.stat().st_size > 0 and mcp_whl.stat().st_size > 0
    except Exception as exc:
        ui.stop_spinner(False, "", f"Failed to extract wheels: {exc}")
        sys.exit(1)
    ui.stop_spinner(ok, "Extracted trw-memory and trw-mcp wheels")
    if not ok:
        ui.step_fail("Extracted wheels are empty")
        sys.exit(1)
    return memory_whl, mcp_whl


def phase_prompt_features(
    ui: UI,
    install_ai: bool | None,
    install_sqlitevec: bool | None,
    prior_extras: dict[str, bool] | None = None,
) -> tuple[bool, bool]:
    """Prompt for optional features (interactive only). Skips if already answered."""
    if prior_extras is None:
        prior_extras = {}

    if install_ai is None or install_sqlitevec is None:
        draw_divider("Optional Features")

    if install_ai is None:
        if prior_extras.get("ai"):
            ui.step_ok("AI extras: already installed")
            install_ai = True
        else:
            print()
            ui.hint("AI extras enable semantic search over your learnings")
            ui.hint("and LLM-powered analysis of patterns across sessions.")
            ui.doc_link("integration#ai-extras")
            install_ai = prompt_yes_no("Install AI/LLM features?")

    if install_sqlitevec is None:
        if prior_extras.get("sqlite_vec"):
            ui.step_ok("sqlite-vec: already installed")
            install_sqlitevec = True
        else:
            print()
            ui.hint("sqlite-vec adds vector similarity search for faster,")
            ui.hint("more relevant recall of past learnings and discoveries.")
            ui.doc_link("integration#vector-search")
            install_sqlitevec = prompt_yes_no("Install sqlite-vec for vector search?")

    return bool(install_ai), bool(install_sqlitevec)


def phase_install_packages(
    ui: UI,
    step: int,
    total: int,
    python: str,
    memory_whl: Path,
    mcp_whl: Path,
) -> None:
    """Phase 3: Install base packages."""
    ui.step_header(step, total, "Installing packages")

    ui.start_spinner("Installing trw-memory...")
    if not pip_install(python, str(memory_whl), "trw-memory", ui):
        ui.stop_spinner(False, "", "pip install failed for trw-memory")
        ui.error("Try installing in a virtual environment:")
        ui.error("  python3 -m venv .venv && source .venv/bin/activate")
        ui.error("  python3 install-trw.py")
        sys.exit(1)
    ui.stop_spinner(True, "Installed trw-memory")

    ui.start_spinner(f"Installing trw-mcp v{TRW_VERSION}...")
    if not pip_install(python, str(mcp_whl), "trw-mcp", ui):
        ui.stop_spinner(False, "", "pip install failed for trw-mcp")
        ui.error("Try installing in a virtual environment:")
        ui.error("  python3 -m venv .venv && source .venv/bin/activate")
        ui.error("  python3 install-trw.py")
        sys.exit(1)
    ui.stop_spinner(True, f"Installed trw-mcp v{TRW_VERSION}")

    # Verify imports
    for mod in ("trw_memory", "trw_mcp"):
        rc = subprocess.run(
            [python, "-c", f"import {mod}"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        ).returncode
        if rc != 0:
            ui.step_fail(f"{mod} not importable after install")
            sys.exit(1)


def phase_install_extras(
    ui: UI,
    step: int,
    total: int,
    python: str,
    install_ai: bool,
    install_sqlitevec: bool,
) -> tuple[int, list[str]]:
    """Install optional extras. Returns (next_step, feature_names)."""
    features: list[str] = []
    s = step

    if install_ai:
        ui.step_header(s, total, "Installing AI extras")
        ui.start_spinner("Installing trw-mcp[ai]...")
        ok = pip_install(python, "trw-mcp[ai]", "trw-mcp[ai]", ui)
        ui.stop_spinner(ok, "AI features enabled", "AI extras failed (non-fatal)")
        if ok:
            features.append("AI/LLM")
        else:
            ui.step_warn("AI extras failed — base TRW still works fine")
        s += 1

    if install_sqlitevec:
        ui.step_header(s, total, "Installing sqlite-vec")
        ui.start_spinner("Installing sqlite-vec...")
        ok = pip_install(python, "sqlite-vec", "sqlite-vec", ui)
        ui.stop_spinner(ok, "sqlite-vec enabled", "sqlite-vec failed (non-fatal)")
        if ok:
            features.append("sqlite-vec")
        else:
            ui.step_warn("sqlite-vec failed — TRW works without it")
        s += 1

    return s, features


def phase_project_setup(
    ui: UI,
    step: int,
    total: int,
    python: str,
    target_dir: Path,
    upgrade_only: bool,
    interactive: bool = False,
    ide: str | None = None,
) -> None:
    """Set up or update the project scaffolding."""
    ui.step_header(step, total, "Setting up project")

    if upgrade_only:
        ui.step_ok("Upgrade complete — skipping project setup")
        return

    if not (target_dir / ".git").is_dir():
        ui.step_warn("Not a git repository — skipping project setup")
        ui.step_warn("After git init, run: trw-mcp init-project .")
        return

    # IDE detection and selection
    detected_clis = _detect_installed_clis()
    detected_ides = _detect_project_ides(str(target_dir))

    resolved_ide: str | None = ide
    is_update = (target_dir / ".trw").is_dir()
    if resolved_ide is None:
        if is_update and interactive and detected_ides:
            # Re-run: use previously configured IDEs without prompting
            resolved_ide = "all" if len(detected_ides) >= 2 else detected_ides[0]
            ui.step_ok(f"IDE config: {', '.join(detected_ides)} (from prior install)")
        elif interactive:
            resolved_ide = _prompt_ide_selection(detected_clis, detected_ides)
        else:
            # Headless: auto-configure all detected CLIs; default to claude-code if none
            all_detected = list(dict.fromkeys(detected_clis + detected_ides))
            if len(all_detected) >= 2:
                resolved_ide = "all"
            elif len(all_detected) == 1:
                resolved_ide = all_detected[0]
            else:
                resolved_ide = "claude-code"

    trw_cmd = find_trw_cmd(python)
    action = "update-project" if is_update else "init-project"
    label = "Updating" if is_update else "Initializing"

    cmd = trw_cmd + [action, str(target_dir)]
    if resolved_ide is not None:
        cmd += ["--ide", resolved_ide]

    ok = run_with_progress(ui, f"{label} project...", cmd)
    ui.stop_spinner(ok, f"Project {'updated' if is_update else 'initialized'}", f"Project {action} failed")


def phase_configure(
    ui: UI,
    step: int,
    total: int,
    target_dir: Path,
    interactive: bool,
    opt_name: str,
    opt_api_key: str,
    opt_telemetry: bool | None,
    prior_config: dict[str, object] | None = None,
) -> str:
    """Configure project identity, API key, and telemetry. Returns platform_status."""
    ui.step_header(step, total, "Configure your project")

    if prior_config is None:
        prior_config = {}

    default_name = sanitize_project_name(target_dir.name)
    project_name = ""
    api_key = ""
    telemetry_enabled = False

    if interactive:
        if prior_config.get("project_name"):
            project_name = str(prior_config["project_name"])
            ui.step_ok(f"Project: {project_name} (from prior install)")
        else:
            draw_divider("Project Identity")
            print()
            ui.hint("This name identifies your installation in the TRW platform.")
            ui.hint("It appears in your analytics dashboard and team views.")
            project_name = _prompt_project_name(ui, default_name)

        if prior_config.get("api_key"):
            ui.step_ok("API key: configured (from prior install)")
            api_key = str(prior_config["api_key"])
            telemetry_enabled = True
        else:
            draw_divider("Platform Connection")
            print()
            ui.hint("Connect to trwframework.com to sync learnings across")
            ui.hint("machines, view analytics, and collaborate with your team.")
            ui.doc_link("integration#platform-connection")
            api_key = _prompt_api_key(ui)

            if api_key:
                telemetry_enabled = True
            elif "telemetry" in prior_config:
                telemetry_enabled = bool(prior_config["telemetry"])
                ui.step_ok(f"Telemetry: {'enabled' if telemetry_enabled else 'disabled'} (from prior install)")
            else:
                print()
                ui.hint("Anonymous telemetry helps us improve TRW for everyone.")
                ui.hint("Only tool usage counts are shared — no code or learnings.")
                ui.doc_link("integration#telemetry")
                telemetry_enabled = prompt_yes_no("Enable anonymous usage telemetry?")
                ui.step_ok("Telemetry enabled" if telemetry_enabled else "Telemetry disabled")
    else:
        # Script mode: use flags
        project_name = sanitize_project_name(opt_name) if opt_name else default_name
        if opt_api_key:
            if validate_api_key(opt_api_key):
                api_key = opt_api_key
                telemetry_enabled = True
            else:
                ui.warn("Invalid API key format — ignoring --api-key")
        if not api_key and opt_telemetry is True:
            telemetry_enabled = True
        if opt_telemetry is False:
            telemetry_enabled = False
        ui.step_ok(f"Project: {project_name}")

    # Write to config
    config_path = target_dir / ".trw" / "config.yaml"
    if update_config(config_path, project_name, api_key, telemetry_enabled):
        ui.step_ok("Configuration saved to .trw/config.yaml")
    else:
        ui.step_warn("Config file not found — run project setup first")

    if api_key:
        return "connected"
    if telemetry_enabled:
        return "telemetry"
    return "offline"


def _prompt_project_name(ui: UI, default: str) -> str:
    """Interactive project name prompt with sanitization."""
    raw = prompt_input("Project name:", default)
    name = sanitize_project_name(raw)
    if not name:
        name = default
    if not re.match(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?$", name):
        ui.step_warn("Could not sanitize name, using default")
        name = default
    if name != raw and raw:
        ui.step_ok(f"Project name: {name} (sanitized from '{raw}')")
    else:
        ui.step_ok(f"Project name: {name}")
    return name


def _prompt_api_key(ui: UI) -> str:
    """Interactive API key prompt with validation and retries."""
    max_attempts = 3
    for attempt in range(max_attempts):
        raw = prompt_input("Platform API key (Enter to skip):").strip()
        if not raw:
            ui.step_ok("No API key — offline mode")
            return ""
        if validate_api_key(raw):
            ui.step_ok("API key accepted")
            return raw
        remaining = max_attempts - attempt - 1
        if remaining > 0:
            ui.step_warn("Invalid format (must start with trw_, alphanumeric only). Try again:")
        else:
            ui.step_warn("Invalid format — skipping API key")
    return ""


# ── Main ─────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install TRW Framework in a project directory.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Interactive mode (default in a terminal):\n"
            "  Guided setup with prompts, spinners, and feature selection.\n\n"
            "Script mode (piped input or --script):\n"
            "  No prompts. Use flags to configure.\n\n"
            "Examples:\n"
            "  python3 install-trw.py                       # Interactive\n"
            "  python3 install-trw.py --ai --telemetry      # With extras\n"
            "  python3 install-trw.py --script --no-ai      # Headless\n"
            "  python3 install-trw.py --upgrade             # Upgrade only\n"
        ),
    )
    parser.add_argument("target_dir", nargs="?", default=".", help="Project directory")
    parser.add_argument("--upgrade", action="store_true", help="Upgrade package only")
    parser.add_argument("--ai", dest="install_ai", action="store_true", default=None, help="Install AI/LLM extras")
    parser.add_argument("--no-ai", dest="install_ai", action="store_false", help="Skip AI extras")
    parser.add_argument("--sqlite-vec", dest="install_vec", action="store_true", default=None, help="Install sqlite-vec")
    parser.add_argument("--no-sqlite-vec", dest="install_vec", action="store_false", help="Skip sqlite-vec")
    parser.add_argument("--quiet", "-q", action="store_true", help="Minimal output")
    parser.add_argument("--script", action="store_true", help="Force non-interactive mode")
    parser.add_argument("--name", default="", help="Project name (installation ID)")
    parser.add_argument("--api-key", default="", help="Platform API key")
    parser.add_argument("--telemetry", dest="telemetry", action="store_true", default=None, help="Enable telemetry")
    parser.add_argument("--no-telemetry", dest="telemetry", action="store_false", help="Disable telemetry")
    parser.add_argument(
        "--ide",
        choices=["claude-code", "opencode", "all"],
        default=None,
        help="Target IDE to configure (prompted if not specified in interactive mode)",
    )

    args = parser.parse_args()

    # Mode detection
    interactive = (not args.script) and sys.stdin.isatty()

    # Script-mode defaults
    install_ai = args.install_ai
    install_vec = args.install_vec
    if not interactive:
        install_ai = install_ai if install_ai is not None else False
        install_vec = install_vec if install_vec is not None else False

    # Resolve target
    target_dir = Path(args.target_dir).resolve()
    if not target_dir.is_dir():
        print(f"{RED}[TRW]{NC} Directory not found: {target_dir}", file=sys.stderr)
        sys.exit(1)

    ui = UI(interactive=interactive, quiet=args.quiet)

    show_banner(ui)

    # Load prior installation state (before python check — no python needed yet)
    prior_config = _load_prior_config(target_dir)
    is_reinstall = bool(prior_config)

    if is_reinstall and interactive:
        ui.info("Existing TRW installation detected — reusing prior settings")

    # Calculate step count
    total = 4  # python + extract + install + project-setup
    has_config = interactive or args.name or args.api_key
    # We may not know ai/vec yet in interactive mode, so add after prompt
    # Use a mutable list so phases can reference the final count
    extra = 0
    if install_ai:
        extra += 1
    if install_vec:
        extra += 1
    if has_config:
        extra += 1
    total += extra

    # Create temp dir for wheel extraction
    tmpdir = Path(tempfile.mkdtemp(prefix="trw-install-"))
    try:
        # Phase 1: Python check
        python = phase_check_python(ui, 1, total)

        # Detect already-installed extras now that we have the python path
        prior_extras: dict[str, bool] = _detect_installed_extras(python) if is_reinstall else {}

        # Phase 2: Extract wheels
        memory_whl, mcp_whl = phase_extract_wheels(ui, 2, total, tmpdir)

        # Feature prompts (between extract and install)
        if interactive:
            install_ai, install_vec = phase_prompt_features(
                ui, install_ai, install_vec, prior_extras=prior_extras,
            )
            # Recalculate total now that we know selections
            total = 4
            if install_ai:
                total += 1
            if install_vec:
                total += 1
            if has_config:
                total += 1

        install_ai = bool(install_ai)
        install_vec = bool(install_vec)

        # Phase 3: Install base packages
        phase_install_packages(ui, 3, total, python, memory_whl, mcp_whl)

        # Phase 3+: Install extras
        next_step, features = phase_install_extras(ui, 4, total, python, install_ai, install_vec)

        # Phase N: Project setup
        phase_project_setup(
            ui, next_step, total, python, target_dir, args.upgrade,
            interactive=interactive,
            ide=args.ide,
        )
        next_step += 1

        # Phase N+1: Configure
        platform_status = "offline"
        if has_config:
            platform_status = phase_configure(
                ui, next_step, total, target_dir, interactive,
                args.name, args.api_key, args.telemetry,
                prior_config=prior_config,
            )

        # Done!
        show_success_banner(ui, platform_status, features)

    finally:
        try:
            shutil.rmtree(tmpdir)
        except OSError:
            pass


if __name__ == "__main__":
    main()

# ── Embedded wheel data (do not edit below this line) ────────────────
# __MEMORY_WHEEL_DATA__
# {{MEMORY_WHEEL_BASE64}}
# __WHEEL_DATA__
# {{WHEEL_BASE64}}
