#!/usr/bin/env bash
# install-trw.sh — Self-contained TRW Framework installer
# Generated by: python scripts/build_installer.py
# Version: {{VERSION}}
#
# Usage:
#   bash install-trw.sh           # Install in current directory
#   bash install-trw.sh /path/to  # Install in specified directory
#   bash install-trw.sh --upgrade # Upgrade package only (skip init-project)
#
# Re-run with a newer version of this script to upgrade.

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────
WHEEL_FILENAME="{{WHEEL_FILENAME}}"
TRW_VERSION="{{VERSION}}"
MIN_PYTHON_VERSION="3.10"

# ── Color output ──────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[TRW]${NC} $*"; }
warn()  { echo -e "${YELLOW}[TRW]${NC} $*"; }
error() { echo -e "${RED}[TRW]${NC} $*" >&2; }

# ── Python version check ─────────────────────────────────────────────
find_python() {
    local py=""
    for candidate in python3 python; do
        if command -v "$candidate" &>/dev/null; then
            py="$candidate"
            break
        fi
    done

    if [ -z "$py" ]; then
        error "Python not found. Install Python >= ${MIN_PYTHON_VERSION}"
        exit 1
    fi

    local major minor
    major=$("$py" -c "import sys; print(sys.version_info.major)")
    minor=$("$py" -c "import sys; print(sys.version_info.minor)")

    if [ "$major" -lt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -lt 10 ]; }; then
        error "Python ${major}.${minor} found but >= ${MIN_PYTHON_VERSION} required"
        exit 1
    fi

    info "Using Python ${major}.${minor} ($py)" >&2
    echo "$py"
}

# ── Extract embedded wheel ────────────────────────────────────────────
extract_wheel() {
    local python_cmd="$1"
    local dest="$2"

    # Use Python for cross-platform base64 decode (works on macOS + Linux)
    sed -n '/^__WHEEL_DATA__$/,$ p' "$0" \
        | tail -n +2 \
        | "$python_cmd" -c "
import sys, base64
data = sys.stdin.read().strip()
sys.stdout.buffer.write(base64.b64decode(data))
" > "$dest"
}

# ── Main ──────────────────────────────────────────────────────────────
main() {
    local upgrade_only=false
    local target_dir="."

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --upgrade)
                upgrade_only=true
                shift
                ;;
            --help|-h)
                echo "Usage: bash install-trw.sh [OPTIONS] [TARGET_DIR]"
                echo ""
                echo "Install TRW Framework in a project directory."
                echo ""
                echo "Arguments:"
                echo "  TARGET_DIR    Project directory (default: current directory)"
                echo ""
                echo "Options:"
                echo "  --upgrade     Upgrade package only, skip project setup"
                echo "  --help, -h    Show this help message"
                exit 0
                ;;
            *)
                target_dir="$1"
                shift
                ;;
        esac
    done

    target_dir="$(cd "$target_dir" 2>/dev/null && pwd)" || {
        error "Directory not found: $target_dir"
        exit 1
    }

    echo -e "${BOLD}TRW Framework Installer v${TRW_VERSION}${NC}"
    echo ""

    # 1. Find Python
    local python_cmd
    python_cmd=$(find_python)

    # 2. Extract embedded wheel
    local tmpdir
    tmpdir=$(mktemp -d)
    trap 'rm -rf "$tmpdir"' EXIT

    info "Extracting embedded package..."
    local wheel_path="${tmpdir}/${WHEEL_FILENAME}"
    extract_wheel "$python_cmd" "$wheel_path"

    if [ ! -s "$wheel_path" ]; then
        error "Failed to extract wheel data"
        exit 1
    fi

    # 3. Install the wheel (try normal, then --user, then --break-system-packages)
    info "Installing trw-mcp v${TRW_VERSION}..."
    if "$python_cmd" -m pip install --upgrade "$wheel_path" --quiet 2>/dev/null; then
        :
    elif "$python_cmd" -m pip install --upgrade --user "$wheel_path" --quiet 2>/dev/null; then
        info "Installed with --user (PEP 668 managed environment)"
    elif "$python_cmd" -m pip install --upgrade --break-system-packages "$wheel_path" --quiet 2>/dev/null; then
        warn "Installed with --break-system-packages (consider using a venv)"
    else
        error "pip install failed — try installing in a virtual environment:"
        error "  python3 -m venv .venv && source .venv/bin/activate"
        error "  bash install-trw.sh"
        exit 1
    fi

    # Verify
    if ! "$python_cmd" -c "import trw_mcp" 2>/dev/null; then
        error "Installation failed — trw_mcp module not importable"
        exit 1
    fi
    info "Package installed successfully"

    # 4. Run init-project (unless --upgrade)
    if [ "$upgrade_only" = true ]; then
        info "Upgrade complete (--upgrade flag: skipping project setup)"
    elif [ -d "${target_dir}/.git" ]; then
        info "Setting up TRW in ${target_dir}..."

        # Prefer the CLI entry point, fall back to python -m
        if command -v trw-mcp &>/dev/null; then
            trw-mcp init-project "${target_dir}"
        else
            "$python_cmd" -m trw_mcp.server init-project "${target_dir}"
        fi
    else
        warn "Not a git repository — skipping project setup."
        warn "After initializing git, run: trw-mcp init-project ."
    fi

    # 5. Success
    echo ""
    echo -e "${GREEN}${BOLD}TRW Framework v${TRW_VERSION} — ready${NC}"
    echo ""
    info "Next steps:"
    info "  1. Edit CLAUDE.md with your project details"
    info "  2. Start Claude Code:  claude"
    info "  3. TRW tools are automatically available"
    echo ""
    info "To upgrade later, re-run this script with a newer version."
}

main "$@"
exit 0

# ── Embedded wheel data (do not edit below this line) ─────────────────
__WHEEL_DATA__
{{WHEEL_BASE64}}
