"""State-assertion classifier for the FR05 validity-window nudge (PRD-CORE-244).

A learning that records an *invariant* stays true. A learning that records
*state* is true the day it is written and silently false later, and nothing on
the record marks which kind it is — ``expires`` was measured non-empty on 0 of
9,366 rows.

This module proposes a window. It never sets one. Silent stamping is prohibited
by the requirement rather than merely discouraged: a classifier that puts a TTL
on an invariant makes the store LESS true than one that puts none anywhere, and
this heuristic will misfire in both directions. So the author decides, and the
only output is advisory text.

NFR01: a pure string operation — no filesystem, no network, no config I/O beyond
the already-resolved ``TRWConfig`` the caller hands in.
"""

from __future__ import annotations

import re
from datetime import timedelta

__all__ = ["STATE_ASSERTION_MARKERS", "propose_validity_window", "validity_window_nudge"]

#: Phrases that mark a claim about *current* state rather than an invariant.
#: Each is matched case-insensitively on a word boundary. Every one of them is
#: an explicit TEMPORAL qualifier — the author has already said "this is true
#: now", which is the only signal strong enough to justify proposing a TTL.
#:
#: Deliberately multi-word where ambiguity exists: a bare "today" or "still"
#: appears in ordinary narration of a defect ("regenerated by update-project
#: today") and would reintroduce the false-positive class FR08 removes.
_MARKER_PHRASES = (
    "currently",
    "not yet",
    "is now",
    "as of",
    "at present",
    "at the moment",
    "at this time",
    "right now",
    "for now",
    "so far",
    "no longer",
)

_MARKER_PATTERNS = tuple(re.compile(rf"\b{re.escape(phrase)}\b", re.IGNORECASE) for phrase in _MARKER_PHRASES)

#: Exposed for tests and for the tool docstring that explains the nudge.
STATE_ASSERTION_MARKERS = _MARKER_PHRASES


def propose_validity_window(
    summary: str,
    detail: str,
    learning_type: str,
    ttl_days_by_type: dict[str, int],
) -> timedelta | None:
    """Return a proposed validity window for a state-asserting learning.

    Args:
        summary: The learning's one-line summary.
        detail: The learning's full context.
        learning_type: The ``type`` field — ``convention`` and ``pattern``
            record invariants and are never given a window, whatever the text
            says.
        ttl_days_by_type: ``TRWConfig.state_learning_default_ttl_days`` — the
            per-type default window. A type absent from the table gets no
            proposal, which is how the invariant types opt out by configuration
            rather than by a hard-coded list.

    Returns:
        The proposed window, or ``None`` when the learning does not look like a
        state assertion (or its type records invariants).

    PRD-FIX-141-FR08 removed the second trigger: a BARE CARDINAL ("7 callers",
    "0 edges") used to be sufficient on its own, on the reasoning that a number
    that was measured is a number that changes. Measured against the seven
    defect records written on 2026-09-16, that reasoning fired on all seven and
    the temporal markers on none: every record of a defect quantifies it, so the
    trigger selected almost exactly the class of learning that must NOT expire.
    A record that says a surface is broken states a durable property until
    somebody fixes it, and a TTL on it makes the store less true — which is the
    failure this module's own docstring says it exists to avoid.

    The false negative this accepts, stated plainly: a genuine state claim
    carrying a count and NO temporal qualifier ("embedding coverage is 9 of
    1343") now gets no proposal. That is the cheaper error. The author can still
    set a window, and the nudge no longer trains readers to ignore it.
    """
    ttl_days = ttl_days_by_type.get(learning_type.strip().lower())
    if not ttl_days:
        return None
    text = f"{summary}\n{detail}"
    if not any(pattern.search(text) for pattern in _MARKER_PATTERNS):
        return None
    return timedelta(days=ttl_days)


def validity_window_nudge(learning_id: str, window: timedelta) -> str:
    """Render the advisory text naming the window and the call that sets it.

    Naming the exact update call matters: ``expires`` was removed
    from the public ``trw_learn`` signature on 2026-07-28, so an author told only
    "consider setting a window" has no reachable way to act on it.
    """
    days = window.days
    return (
        f"This reads like a claim about current state, which is true today and silently "
        f"false later. If it is, give it a window ({days} days is the default for this "
        f"type): trw_learn(learning_id='{learning_id}', metadata={{'expires': "
        f"'<YYYY-MM-DD>'}}). If it states a durable invariant instead, restate it as one "
        f"and ignore this."
    )
